### ISSUE TITLE
Browsing Local Filesystem?

### ISSUE THREAD

**Issue by diskotechjam** [arybczak/ncmpcpp#104]
Is it possible to browse/play files outside of the MPD directory? Ncmpcpp's description says it possible, but for some reason I cannot figure it out. I've tried changing the directory location in the config file, ignoring folders in the mpd library, and I've read through the manpage, but I suspect there is something I'm missing.

**Comment by slavaGanzin** [comment]
you need to connect via mpd socket and then press "browse tab" ("1" or "2" by default) twice.

**Comment by arybczak** [comment]
Exactly.
