### ISSUE TITLE
crash when searching

### ISSUE THREAD

**Issue by Phenitei** [arybczak/ncmpcpp#106]
While using the search panel (3 key in the default bindings), if the add song to playlist keybinding is pressed (a in default bindings) ncmpcpp will crash with the following error:
```
Fetching selected songs...ncmpcpp: search_engine.cpp:351: virtual std::vector<MPD::Song> SearchEngine::getSelectedSongs(): Assertion `w.current()->value().isSong()' failed.
Aborted (core dumped)
```
attached is the coredump. Please tell me if you need more info.
[coredump.zip](https://github.com/arybczak/ncmpcpp/files/88853/coredump.zip)

**Comment by arybczak** [comment]
Fixed in 0.7.2.
