### ISSUE TITLE
not running on Ubuntu 15.10

### ISSUE THREAD

**Issue by miko007** [arybczak/ncmpcpp#108]
since upgrading to Ubuntu 15.10 i get the following error when trying to start ncmpcpp:

```
Error while processing configuration: bad lexical cast: source type value could not be interpreted as target
```

this occurs on both, the version from the official apt-repo an the self compiled version.

**Comment by arybczak** [comment]
You most likely have in the config an option that is expected to be a number but is not.

**Comment by miko007** [comment]
it is the config coming with the most recent version on this git repo. how can i track this down?

**Comment by arybczak** [comment]
What if you delete/move the file then?

**Comment by miko007** [comment]
if i remove the folder `.ncmpcpp` and then start the program. it creates the folder again (empty) and crashes with the same error message.

**Comment by miko007** [comment]
i finally can track the issue down. i am connecting via the environment variables:

```bash
export MPD_HOST=host.domain.tld
export MPD_PORT=12345
```

the error only occurs, if those are set. did you recently change the use of this variables?

**Comment by arybczak** [comment]
You must've had MPD_PORT set to something that wasn't a number.

Error message improved by 8dde3944ee1878a7f26dd24bfe5e31f4e72c05b1.

**Comment by arybczak** [comment]
Or maybe you had whitespace around it.
