### ISSUE TITLE
Error while writing tags in ...

### ISSUE THREAD

**Issue by ceraph** [arybczak/ncmpcpp#109]
Hi,
every time I try to change some tag for an album I get the error message "Error while writing tags" followed by the file name. I'm on Arch Linux.

**Comment by arybczak** [comment]
Hey,

Either you don't have write permissions or you've set wrong path to mpd music directory in ncmpcpp config file.

**Comment by ceraph** [comment]
Thank you for the quick reply. I feel rather stupid for not thinking about the config. It works now.
