### ISSUE TITLE
Allow sorting by album in media library.

### ISSUE THREAD

**Issue by ivegotasthma** [arybczak/ncmpcpp#114]
Hello,

Sometimes an album will have multiple arists which all have the same album and the names will be scattered through the whole library. I was wondering if there is way to sort the songs by album. Currently I don't see an option to sort by album only.

**Comment by cronokun** [comment]
Hey, @ivegotasthma! There is an option in config: `media_library_primary_tag = album_artist`. So you can tag albums with album artist "Various Artists" for compilations.

**Comment by Ivoz** [comment]
+1 I want to sort by Album Name.

I do not want to sort by Artist, nor by Album Artist. Searching my library by artist just leaves me mostly lost.

**Comment by soredake** [comment]
Still no support, sadly.

**Comment by Polochon-street** [comment]
I'm trying to replace the "Albums (sorted by artist)" view with a plain "Albums" view right now, but I'm a bit lost with the code's structure. Could somebody with some insight could maybe point out a general direction/files where I should look?

**Comment by Polochon-street** [comment]
Just did a very very very ugly change to replace the current "Album (sorted by artists)" view by an "Album" view, here's the branch: https://github.com/Polochon-street/ncmpcpp/tree/album-view

I'm not even sure what's going on, but it seems to work, will try to clean it if I have time in the next few days.

**Comment by Polochon-street** [comment]
https://github.com/arybczak/ncmpcpp/pull/240 should work (and not be too ugly) now. The old album-artist view is not replaced anymore, it still exists.

**Comment by soredake** [comment]
@arybczak

**Comment by ivegotasthma** [comment]
I'm cleaning up by profile and I'll close the issue. Thanks!
