### ISSUE TITLE
Download lyrics of the songs

### ISSUE THREAD

**Issue by kevinisaac** [arybczak/ncmpcpp#115]
It will be nice to have an option to download lyrics of all songs in a playlist/directory/database, so that users can view lyrics while playing a song the first time when not connected to the internet.

**Comment by slavaGanzin** [comment]
Ah? https://github.com/arybczak/ncmpcpp/blob/master/doc/config#L19

**Comment by kevinisaac** [comment]
@slavaGanzin: I'm not sure if you understand what I meant. It's not about the lyrics directory. It's about an easier way (a single click something like `<Ctrl-L>`?) to download lyrics of all songs in the current or a specific playlist.

**Comment by arybczak** [comment]
Have a look at 00f70e23e668a6ad13006dbbf160a256ab319323.
