### ISSUE TITLE
Visualizer under Cygwin

### ISSUE THREAD

**Issue by klonuo** [arybczak/ncmpcpp#117]
Hi,

I've build ncmpcpp on Cygwin, and everything is perfect except that I can't see visualizer:

`Counldn't open "/tmp/mpd.fifo" for reading PCM data: Device or resource busy`

My settings are correct as in my Ubuntu box, and FIFO output device is active and `/tmp/mpd.fifo` exists, but I get above error.

Any ideas how to resolve?

**Comment by arybczak** [comment]
See http://www.unix.com/unix-desktop-for-dummies-questions-and-answers/117429-cygwin-error-device-resource-busy.html

I'm guessing it's because MPD has it opened, so ncmpcpp can't simultanously open it.

**Comment by klonuo** [comment]
Seems like Cygwin bug: https://www.cygwin.com/ml/cygwin/2013-01/msg00292.html

I'll close
