### ISSUE TITLE
Request: Show track bitrate in Playlist, also some format info

### ISSUE THREAD

**Issue by Blum** [arybczak/ncmpcpp#119]
Could we have the bitrate info in the playlist. I have same songs in multiple formats, now I need to play them first just to see their (current) bitrate.  
It would be also very helpful if we have some audio sample info like "24bit / 192KHz".

Thank you all, this player is awesome.

**Comment by arybczak** [comment]
MPD is capable to show bitrate for the current song only (and no format information).
