### ISSUE TITLE
Hangs with 100 % cpu usage when no stdin is provided

### ISSUE THREAD

**Issue by trygveaa** [arybczak/ncmpcpp#121]
If you start ncmpcpp without a stdin, e.g. `ncmpcpp < /dev/null`, it opens, but uses 100 % cpu and is unresponsive.

You might be wondering why I'm starting it without stdin, but what I did was start it from my WMs launcher without thinking about that it wouldn't open a terminal.

It should probably exit with an error if it can't read from stdin (unless it can work without stdin).

Edit: Version 0.7.3, currently newest btw.

**Comment by jgrar** [comment]
I can confirm this behaviour when running `ncmpcpp < /dev/null`.

btw @trygveaa what window manager are you using? I'm launching it fine in dwm with `spawn()` and `ncmpcpp &` from a terminal. It seems strange to me that a window manager would launch applications with `< /dev/null` by default.

**Comment by arybczak** [comment]
> it opens, but uses 100 % cpu and is unresponsive.

Well, of course it is unresponsive when there is no input stream :P It looks like window timeouts etc. don't work in this case, so it just spins in the main loop, hence the CPU consumption. Other than that it works fine.

Presumably it should check in Window::readKey whether stdin is valid and if not, just abort. Patches are welcome.

**Comment by jgrar** [comment]
@arybczak I've tried `< /dev/null` on other ncurses based applications and it looks like they just quit gracefully like you've suggested. It shouldn't be being launched like that but it should also be brought in line with other ncurses applications.

**Comment by czipperz** [comment]
Maybe adding an `istty()` check at the beginning of `main()` would help?

**Comment by czipperz** [comment]
This would have the problem that `ncmpcpp < commands` would break.  Not sure if that is a use case.

**Comment by tinkerttoy** [comment]
@czipperz Try `echo s | ncmpcpp`. It'll stop the playlist, but then OP's behavior will happen: unresponsive, CPU blows up. Without really diving into the code, I'd conclude that ncmcpp has no idea how to handle streams. Like, at all.

If you want to preserve the `ncmpcpp < commands` use case, then the solution would be to implement an EOF handler. On EOF, you could either close the program, or open stdin and read from that until the user quits normally.

**Comment by trygveaa** [comment]
@jgrar: Oh, sorry for not responding. I'm using awesome.

**Comment by arybczak** [comment]
See 9306f56c3400b596b91c4d2515dd5fcd8e948748.
