### ISSUE TITLE
Inputing \ in find forward segmentation faults

### ISSUE THREAD

**Issue by lol10801lol** [arybczak/ncmpcpp#122]
ncmpcpp 0.7.3, pressing / to enter find forward mode then pressing \ crashes ncmpcpp with the following error: “ncmpcpp” terminated by signal SIGSEGV (Address boundary error)

**Comment by arybczak** [comment]
This is not a global issue, it's most likely related to your boost/icu libraries.

**Comment by arybczak** [comment]
That's 99% related to a wrong ABI version of icu/boost. Recompile ncmpcpp against your current boost/icu and reopen if doesn't fix the problem or if you use binary distro and ncmpcpp is a binary package, fill a bug for your distribution.
