### ISSUE TITLE
Fetch lyrics from filename heuristics if song lacks artist and title tags

### ISSUE THREAD

**Issue by liquiddandruff** [arybczak/ncmpcpp#124]
A good amount of my songs don't have artist/title metadata set but are named like this: `{Artist/AlbumArtist} - {Title}`

When fetching lyrics on these songs, it would be nice to not need to edit the tags and just try searching for lyrics based on a simple heuristics like above (maybe make it configurable too?).

Thanks!

**Comment by arybczak** [comment]
Duplicate of #72. Also, solved on master.
