### ISSUE TITLE
SIGTRAP Error

### ISSUE THREAD

**Issue by wickedwzrd** [arybczak/ncmpcpp#125]
I'm on osx and just updated my homebrew, then tried to start ncmpcpp and got this error:
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.56.dylib
  Referenced from: /usr/local/bin/ncmpcpp
  Reason: image not found
fish: 'ncmpcpp' terminated by signal SIGTRAP (Trace or breakpoint trap)

If you know what could be causing this error, I would be greatly appreciated.

**Comment by UniqMartin** [comment]
Homebrew maintainer speaking here. The issue will be resolved shortly (see Homebrew/brew#90). Also, as that is an oversight from the `icu4c` update and specific to Homebrew, the appropriate place to report it next time would be: https://github.com/Homebrew/homebrew-core/issues Thanks!

**Comment by arybczak** [comment]
@UniqMartin Thanks for the investigation.
