### ISSUE TITLE
F1 key is conflicted with xfce4-terminal

### ISSUE THREAD

**Issue by hillz1** [arybczak/ncmpcpp#126]
The help key `F1` of `ncmpcpp` is conflicted with the help key of `xfce-terminal`, every time I press `F1` it always shows up the help page of `xfce-terminal` instead of the help page of `ncmpcpp` and there's no way to change the key on `xfce-terminal`. Can you change `F1` to something else that won't have conflict with other packages?

**Comment by jgrar** [comment]
Ncmpcpp key bindings are configured in "~/.ncmpcpp/bindings" use the example file from "/usr/share/doc/ncmpcpp/bindings"

**Comment by arybczak** [comment]
What @jgrar mentioned. You can rebind switching to help screen.
