### ISSUE TITLE
ncmpcpp fails to load due to dyld library error

### ISSUE THREAD

**Issue by mrzool** [arybczak/ncmpcpp#128]
Getting this error when trying to launch ncmpcpp:

    dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.56.1.dylib
        Referenced from: /usr/local/opt/boost/lib/libboost_locale-mt.dylib
        Reason: image not found
    Trace/BPT trap: 5

I'm on OS X and installed ncmpcpp through homebrew. Not sure how to fix or where to report.

**Comment by adkow** [comment]
See #125.

**Comment by mrzool** [comment]
Fixed by reinstalling boost as suggested [here](https://github.com/Homebrew/homebrew-core/issues/395).

    brew reinstall boost
