### ISSUE TITLE
Error: /boost/thread.hpp is missing

### ISSUE THREAD

**Issue by spudnica** [arybczak/ncmpcpp#135]
Hi!

The bug with boost was known due to -mt suffix, but I think it is not issue at my place since I tried solution with setting lib boost suffix to "".

When I try to compile ncmpcpp on Debian 7.1 64 bit I get error: 

`configure: error: boost/thread.hpp is missing or your boost version is too old (boost.thread v3 is required)`

I installed all boost-libs with:

`sudo apt-get install libboost-all-dev`
But its already the newest version.

I am linux beginner so any basic solutions may be untested.

**Comment by mineo** [comment]
Debian 7 might just be too old - it only provides boost 1.49 which (iirc) only contains boost.thread v2 or so.

**Comment by arybczak** [comment]
@minteo is correct, closing.
