### ISSUE TITLE
Playlist sort not working

### ISSUE THREAD

**Issue by DasHammett** [arybczak/ncmpcpp#136]
Hi, 

Sorting a playlist function is not working at all. When I select Sort option, "pop-up" screen does not go away and sorting has not happened. I cannot move the tag order either.

ncmpcpp: 0.7.3 
mpd: 0.19.14
boost: 1.60
ncurses: 5.9-r99
curl: 7.45
readline: 6.3p8
taglib: 1.9.1-r2

Thank you

**Comment by ZitZ** [comment]
It seems to work for me. m and n move items up and down respectively, and then hit enter on sort, and it sorts the playlist.

**Comment by DasHammett** [comment]
Hi, 

Sorry for the late reply. It does not work for me. Whenever I add a new album to the existing playlist, ncmpcpp puts it at the end and I cannot sort the list to be placed by Artist. 

Ncmpcpp can read the ID3v1 tag correctly, but it does not sort. I need to clean the playlist and add again in order to have it sorted, which is inconvenient.

**Comment by arybczak** [comment]
You need to increase max_command_list_size parameter in mpd.conf if you plan to sort big playlists.
