### ISSUE TITLE
unable to edit tags

### ISSUE THREAD

**Issue by SavoyRoad** [arybczak/ncmpcpp#144]
With running mpd as the current user, I am unable to edit any tags in the Tag Editor.  The music directory in both the mpd and ncmpcpp config files match and point to to the correct directory, and the music library is located on an NFS mount which my user has full read/write access to as well.  The error log in my .ncmpcpp directory remains empty, with the only error message popping up on the status bar when I try to save the tags:

`Error while writing tags in "Song Name.flac"`

The only solutions I have been able to find online have been related to permissions errors.

Version is 0.7.4 on Debian Stretch, and I have `libtag1v5 1.9.1-2.4` installed as well.

**Comment by arybczak** [comment]
Are you sure you have write access to files?

**Comment by arybczak** [comment]
Detailed error message is now displayed on failure, that should help with diagnosis in the future.
