### ISSUE TITLE
Using original date instead of release date.

### ISSUE THREAD

**Issue by michalrus** [arybczak/ncmpcpp#145]
Hey,

how can we use album’s original date (everywhere where track’s release date is used), and only fallback to release date, when the former is not available?

Thank you!

**Comment by lukasgierth** [comment]
Same problem for me. I also would like the original year.

**Comment by carnager** [comment]
so would many. But mpd dev refuses to add support for it, it was requested multiple times.

**Comment by michalrus** [comment]
@carnager, do you have a link to the discussion? What’s his line of argumentation?

**Comment by arybczak** [comment]
I don't get it, please elaborate.

**Comment by carnager** [comment]
@michalrus thats the one i personally requested: https://bugs.musicpd.org/view.php?id=4164

**Comment by carnager** [comment]
@arybczak see 2nd bug report for detailed description why this tag exists.

**Comment by michalrus** [comment]
> Just put the date you wish to use in the "DATE" tag. For the rest, use "readcomments".
>
> We can't make each and every new tag that gets invented by somebody and his dog a new "core" tag.

What… :stuck_out_tongue_closed_eyes:

**Comment by carnager** [comment]
fun fact: "readcomments" does not work with mp3. It also does not integrate with MPDs database, so you cannot search for those tags. Basically it's useless.

**Comment by arybczak** [comment]
It looks like this can't be fixed.

**Comment by Holzhaus** [comment]
Can we reopen this? Looks like this can be fixed now, since [support for the OriginalDate has now been added](https://github.com/MusicPlayerDaemon/MPD/commit/ccb4f44caf34c9d24ab5b4c7404be75effc69cb2).

**Comment by Holzhaus** [comment]
Looks like MusicPlayerDaemon/libmpdclient@e5d0e50d955ad94cf347fcfadd3b2f3a443deb01 added `OriginalDate` support to libmpdclient, but currently that addition is only in git master and has not yet been released/tagged.
