### ISSUE TITLE
Freezes if mpd playlist_directory doesn't exist

### ISSUE THREAD

**Issue by Gilwyad** [arybczak/ncmpcpp#147]
If I have a faulty MPD config (playlist_directory doesn't exist) then ncmpcpp will freeze (when opening the playlist editor with 5) in what looks like an infinite loop, until the directory is created.

**Comment by arybczak** [comment]
Fixed in 0.7.6_dev.

**Comment by remembertoremind** [comment]
Hi. I can reproduce this.

As the first command in this thread suggested, I created the directory .mpd/playlists and uncommented 
`playlist_directory              "~/.mpd/playlists"`
Now ncmpcpp stops freezing.

I'm on Arch Linux with everything updated to newest version.

**Comment by tylernewnoise** [comment]
I can confirm this, too.
mpd version is 0.21.4
ncmpcpp version is 0.8.2
ArchLinux 4.20.0

- `playlist_directory "~/.config/mpd/playlists"` is uncommented in `mpd.conf` and exists -> everything works fine.
- if it's uncommented but non existend, it still works (even though mpd complains at startup).
- if is not in the `mpd.conf` ncmpcpp hangs/freezes.

**Comment by yuri1969** [comment]
@arybczak I can confirm this problem is present using `ncmpcpp 0.8.2` and `mpd 0.21.4` under Gentoo.
