### ISSUE TITLE
off-by-one-error when running this delete sequence

### ISSUE THREAD

**Issue by cryptopsy1** [arybczak/ncmpcpp#149]
this sequence deletes a file from the drive and from the playlist, if you run it twice, the cursor will be on the 'nth+1' item and delete it, when its supposed to delete the nth, on the 2nd call. Version 0.7.5 on gentoo.

def_key "d"
 jump_to_browser
 delete_browser_items
 show_playlist
 delete_playlist_items

**Comment by cryptopsy1** [comment]
for example: if files 1,2,3 are in the playlist

'd' will delete 1 (it worked as it should)
'd' will delete 3 (it deletes 3 even though the request is on 2)

**Comment by arybczak** [comment]
Deleting a file in browser automatically deletes it from playlist, so when you go back to playlist and delete playlist item, it'll delete item 2, not 1.
