### ISSUE TITLE
[Suggestion] Allow lyrics (and other screens) be startup screens?

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [arybczak/ncmpcpp#150]
Is there a reason why not all screens can be used as the initial screen with the -s flag? If there is no reason to avoid this, I would be more than happy to make the pull request myself.

**Comment by arybczak** [comment]
Lyrics screen depends on the underlying screen that contains songs and a selected song, so it's not clear what these should be.

**Comment by arybczak** [comment]
4cd94cb4b3419517bfef1471a08ceb1cb438077a
