### ISSUE TITLE
Config doesn't like relative paths

### ISSUE THREAD

**Issue by tinkerttoy** [arybczak/ncmpcpp#151]
I was trying to set up the visualizer when I ran into an odd bug.

I had mpd put the fifo in ~/.ncmpcpp/visualizer.fifo, then added the following line to .ncmpcpp/config:
`visualizer_fifo_path = "~/.ncmpcpp/visualizer.fifo"
`
Although mpd had successfully created the fifo, ncmpcpp didn't see the file, and gave me an error message when I tried to open the visualization screen. Everything else was configured correctly.

I managed to make it work by changing the line to
`visualizer_fifo_path = "/home/my_username/.ncmpcpp/visualizer.fifo"
`
Apparently, ncmpcpp doesn't like relative paths in its config files.

**Comment by arybczak** [comment]
Fixed in 0.7.6_dev.

**Comment by arybczak** [comment]
See ee040635d96ae04bc5af3262127fe34edc8ab96b for more details.
