### ISSUE TITLE
Assertion fails when searching backward in an empty list

### ISSUE THREAD

**Issue by lenerd** [arybczak/ncmpcpp#154]
The [assertion](https://github.com/lenerd/ncmpcpp/blob/e34221f74d1cfb6140cd40bf57dffeb13e8a5408/src/helpers.h#L40) introduced in commit e657089b30742f395f4e07db73e2ddd24384c5cc (Fix crash occurring when searching backward in an empty list) fails, when `NDEBUG` is not defined and I try to search backwards through an empty playlist.

`wrappedSearch` is called with `m.rbegin()`, `m.rcurrent()` and `m.rend()` as arguments by [`search`](https://github.com/lenerd/ncmpcpp/blob/e34221f74d1cfb6140cd40bf57dffeb13e8a5408/src/helpers.h#L66-L68) (with a reference `m` to an instance of `NC::Menu`).

The methods [`rcurrent`](https://github.com/lenerd/ncmpcpp/blob/e34221f74d1cfb6140cd40bf57dffeb13e8a5408/src/menu.h#L356-L357) and [`rcurrentV`](https://github.com/lenerd/ncmpcpp/blob/e34221f74d1cfb6140cd40bf57dffeb13e8a5408/src/menu.h#L361-L362) of `NC::Menu` seem to work incorrect:

If the container is empty, `begin() == end()` and `++current()` points one behind
`end()` resulting in an invalid iterator, which is compared against (and not equal to) `end` during the assertion.

GDB stacktrace:
```
#0  0x00007f1caea4c04f in raise () from /usr/lib/libc.so.6
#1  0x00007f1caea4d47a in abort () from /usr/lib/libc.so.6
#2  0x00007f1caea44ea7 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007f1caea44f52 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00000000005166be in wrappedSearch<std::reverse_iterator<__gnu_cxx::__normal_iterator<NC::Menu<MPD::Song>::Item*, std::vector<NC::Menu<MPD::Song>::Item, std::allocator<NC::Menu<MPD::Song>::Item> > > >, Regex::Filter<MPD::Song> > (begin=..., current=..., end=..., pred=..., wrap=true, skip_current=false) at helpers.h:40
#5  0x0000000000511602 in search<MPD::Song, Regex::Filter<MPD::Song> > (m=..., pred=..., direction=SearchDirection::Backward, wrap=true, skip_current=false) at helpers.h:68
#6  0x000000000053e037 in Playlist::find (this=0xc62ef0, direction=SearchDirection::Backward, wrap=true, skip_current=false) at playlist.cpp:170
#7  0x00000000005c7051 in Statusbar::Helpers::FindImmediately::operator() (this=0xf059e0, s=0xa9aa20 "q") at statusbar.cpp:231
...
```

**Comment by arybczak** [comment]
Fixed in 0.7.6_dev.
