### ISSUE TITLE
Database update doesn't work with mopidy

### ISSUE THREAD

**Issue by sphaugh** [arybczak/ncmpcpp#157]
I run `mopidyctl local scan` and confirm that my files have been picked up, launch ncmpcpp and hit u... Nothing. The client says `ncmpcpp: Cannot send a new command while receiving another response`.

**Comment by sphaugh** [comment]
Is this WAD? Do you want some help on this? I might be able to take a look.

**Comment by arybczak** [comment]
I don't know what WAD means, but I don't use mopidy and can't debug issues specific to it. If you can pinpoint what the issue is it would be great. I suspect it'll require some time with GDB though.

**Comment by sphaugh** [comment]
Working as designed. I'll check it out :)

**Comment by sphaugh** [comment]
It's mopidy's fault, unfortunately :(

https://docs.mopidy.com/en/latest/ext/mpd/#limitations:
> The following items are currently not supported, but should be added in the near future:
> 
> tagtypes is not supported
> Live update of the music database is not supported

**Comment by arybczak** [comment]
FWIW I fixed the loop in c51b27d.
