### ISSUE TITLE
mpd_host setting in config file is not used

### ISSUE THREAD

**Issue by carnager** [arybczak/ncmpcpp#158]
latest ncmpcpp does not interpret mpd_host setting, while setting a host via command line arguments works just fine. 

Version: 0.7.5

**Comment by arybczak** [comment]
Environment variables MPD_HOST and MPD_PORT overwrite the ones in the config, I'm guessing you have them set?

**Comment by arybczak** [comment]
I see it's not documented anywhere though, sigh.

**Comment by arybczak** [comment]
67d4a04
