### ISSUE TITLE
‘waddnwstr’ was not declared in this scope when compiling on Ubuntu Mate 16.10

### ISSUE THREAD

**Issue by Nvreformat** [arybczak/ncmpcpp#166]
g++ version: g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005

Full error log:

> window.cpp: In member function ‘NC::Window& NC::Window::operator<<(const wchar_t*)’:
> window.cpp:1357:23: error: ‘waddwstr’ was not declared in this scope
>  waddwstr(m_window, ws);

> window.cpp: In member function ‘NC::Window& NC::Window::operator<<(wchar_t)’:
> window.cpp:1367:28: error: ‘waddnwstr’ was not declared in this scope
>  waddnwstr(m_window, &wc, 1);
 
> window.cpp: In member function ‘NC::Window& NC::Window::operator<<(const wstring&)’:
> window.cpp:1395:45: error: ‘waddnwstr’ was not declared in this scope
> waddnwstr(m_window, ws.c_str(), ws.length());

**Comment by arybczak** [comment]
Can you try current master?

**Comment by arybczak** [comment]
Also, do you have ncurses**w**5-dev installed?

**Comment by arybczak** [comment]
If it's not resolved, reopen please.
