### ISSUE TITLE
[BUG] Same color, different rendering

### ISSUE THREAD

**Issue by arbitrary-dev** [arybczak/ncmpcpp#167]
Having state_line_color = progressbar_color = 1 results in different colors:
![screenshot-2016-11-28-23 07 04](https://cloud.githubusercontent.com/assets/6984946/20680202/470f97a6-b5c8-11e6-80ac-a97b11df9e62.png)

**Comment by arybczak** [comment]
It's not a bug, just a restriction of predefined format.

It's solved now though, see https://github.com/arybczak/ncmpcpp/blob/51d7c9d7d51d79ed039b9f89bd5270f23e7b47e4/doc/config#L497.
