### ISSUE TITLE
Optional Features mentioned in README which does not exist.

### ISSUE THREAD

**Issue by jkleve** [arybczak/ncmpcpp#169]
I'm assuming there use to be a README with information on the different --enable and --with options you can give ./configure to enable those features. Under 'Optional Features' in INSTALL it mentions this but there is no such README. Can we include what features you can enable in the INSTALL file?

**Comment by arybczak** [comment]
You can get this information from `./configure --help`. If you want this to be mentioned in INSTALL file, patches are welcome.

**Comment by arybczak** [comment]
c48280b4468a4c35bcbb24a348993e5e176bd1f9
