### ISSUE TITLE
Add ability to hide `Reading configuration from ~/.ncmpcpp/config...` message

### ISSUE THREAD

**Issue by onodera-punpun** [arybczak/ncmpcpp#171]
Seems like I can hide it using `ncmpcpp 2>/dev/null`, not the cleanest solution though.

**Comment by bozbalci** [comment]
+1. Would be much cleaner if it was logged elsewhere.

**Comment by arybczak** [comment]
Fixed by 7ba2c3534cc1ff223f6715e58f0da0a4212ad4d7
