### ISSUE TITLE
Add ability to remove the inverse highlighting when selecting an item

### ISSUE THREAD

**Issue by nuclearcoconut42** [arybczak/ncmpcpp#172]
Personally, I really don't like the way highlighting is handled in ncmpcpp, and I think there should be a way to completely disable the highlighting of a selected item and instead use a user-selected prefix/suffix. I just think it would look nicer, and there is currently no way of changing it.

**Comment by TheReverend403** [comment]
How it currently looks: ![before](https://a.pste.pw/EhY.png)

How it should look by default: ![after](https://a.pste.pw/QRe.png)

In other words, bold should be used to emphasise a selection, not background colours.

**Comment by ErraticFox** [comment]
@TheReverend403 I think it should be up to the user. Default it should be some sort of difference, like background. Though if the user goes in the config and makes it so it's not apparent, then that's their decision.

**Comment by arybczak** [comment]
See 19d32648ed4ad04c4cc09fd7ec6b9250b9387893.
