### ISSUE TITLE
ask_before_clearing_playlists doesn't work

### ISSUE THREAD

**Issue by slavaGanzin** [arybczak/ncmpcpp#173]
Hello Andrej. I get a bug with clearing playlists:

STR:
1.```$ cat ~/.config/.ncmpcpp/config  | grep ask_before```
```ask_before_clearing_playlists = no```
2. ```$ ncmpcpp -c ~/.config/.ncmpcpp/config```
3. Add any music
4. Press 'c' or 'C'

and then I get:
```Do you really want to clear main playlist? [y/n] ```

versions:
readline 7.0.001-1
ncurses 6.0+20161203-1

```shell
$ ncmcpp -v
ncmpcpp 0.8_dev

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - outputs
 - visualizer
 - clock

encoding detection: enabled
built with support for: fftw ncurses taglib
```

**Comment by arybczak** [comment]
Fixed by f3713ec2ee46f4d905483399f11defe496ac4174.
