### ISSUE TITLE
ncmpcpp compile fails on debian 8

### ISSUE THREAD

**Issue by quimmeetpays** [arybczak/ncmpcpp#174]
Hi there,

trying to compile on Debian 8, with all dependencies installed, fails on generating settings.o. Configure works ok.

`./configure --prefix=/usr --with-taglib --with-fftw --enable-outputs --enable-visualizer --enable-clock`

`make`
`make  all-recursive`
`make[1]: Entering directory '/home/quim/Applications/ncmpcpp'`
`Making all in src`
`make[2]: Entering directory '/home/quim/Applications/ncmpcpp/src'`
`g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/ncursesw    -I/usr/include/taglib  -g -O2 -std=c++14 -MT settings.o -MD -MP -MF .deps/settings.Tpo -c -o settings.o settings.cpp`
`In file included from strbuffer.h:24:0,`
                ` from menu.h:33,`
                ` from format.h:26,`
                ` from format_impl.h:26,`
                 `from settings.cpp:27:`
`/usr/local/include/boost/lexical_cast.hpp: In instantiation of ‘Target boost::lexical_cast(const Source&) [with Target = std::unique_ptr<LyricsFetcher>; Source = std::basic_string<char>]’:`
`utility/option_parser.h:52:38:   required from ‘DestT verbose_lexical_cast(const string&) [with DestT = std::unique_ptr<LyricsFetcher>; std::string = std::basic_string<char>]’`
`utility/option_parser.h:73:56:   required from ‘std::vector<_RealType> list_of(const string&) [with ValueT = std::unique_ptr<LyricsFetcher>; std::string = std::basic_string<char>]’`
`settings.cpp:381:31:   required from here`
`/usr/local/include/boost/lexical_cast.hpp:46:26: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = LyricsFetcher; _Dp = std::default_delete<LyricsFetcher>]’`
         `return get(result);`
                          `^`
I`n file included from /usr/include/c++/4.9/memory:81:0,`
                 `from /usr/local/include/boost/move/algorithm.hpp:32,`
                 `from /usr/local/include/boost/move/move.hpp:32,`
                 `from /usr/local/include/boost/variant/detail/move.hpp:28,`
                 `from /usr/local/include/boost/variant/detail/initializer.hpp:23,`
                 `from /usr/local/include/boost/variant/variant.hpp:30,`
                 `from /usr/local/include/boost/variant.hpp:17,`
                 `from format_impl.h:24,`
                 `from settings.cpp:27:`
`/usr/include/c++/4.9/bits/unique_ptr.h:356:7: note: declared here`
       `unique_ptr(const unique_ptr&) = delete;`
       `^`
`Makefile:587: recipe for target 'settings.o' failed`

**Comment by arybczak** [comment]
What gcc version is that?

**Comment by quimmeetpays** [comment]
quim:~/| gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by arybczak** [comment]
Doesn't Debian offer a bit newer gcc, i.e. 5? 4.9 is 2.5 years old.

**Comment by arybczak** [comment]
I just checked with gcc 4.9.4 and it compiles. That must be a bug in gcc. If you can't update, use clang instead of gcc.

**Comment by quimmeetpays** [comment]
Exactly the same error using clang (3.5.0-10). libboost version is 1.55, what is yours?

**Comment by arybczak** [comment]
1.62

**Comment by arybczak** [comment]
Hmm, yeah, maybe that's a bug in boost.

**Comment by quimmeetpays** [comment]
I've installed libbost version 1.62 in a non-standard directory, in order to not break installed apps and dependencies.
I'm trying to compile ncmpcpp using LDFLAGS and CPPFLAGS with this libboost directory with no success. Is there any way to instruct configure to get libboost includes and libs from this non standard directory?

**Comment by arybczak** [comment]
Check this: http://homepages.inf.ed.ac.uk/imurray2/compnotes/library_linking.txt

**Comment by arybczak** [comment]
You basically want to include appropriate `-I` flag for location of headers and `-L` for location of libraries in CPPFLAGS and LDFLAGS appropriately.
