### ISSUE TITLE
[Help compile quicker] please

### ISSUE THREAD

**Issue by badfiles** [arybczak/ncmpcpp#175]
You have made a nice client, but it needs 300M of boost stuff and 20 minutes of time to compile. 
Also it generates 45M binary. 
Can it be compiled faster?

**Comment by arybczak** [comment]
As far as boost dependency goes, no.

As for the binary size, it's debug symbols. Compile without -g, strip the binary and you'll get around 2.5MB. Less than 2 MB if you use LTO (assuming that you have somewhat up-to-date toolchain).

Also, you can always use prepackaged version if you're using binary distribution.

**Comment by badfiles** [comment]
Thank you, it's much better now. I also build with -j1 now, it goes much faster.
