### ISSUE TITLE
configure: error: no readline compatible library found

### ISSUE THREAD

**Issue by ecl1ps3** [arybczak/ncmpcpp#176]
When i try to compile ncmpcpp for my raspberry pi (running raspbian 8/jessie) i get the error `configure: error: no readline compatible library found` when running ./configure
I've looked around, but cannot understand what library it is referring to.
Does anyone know what I'm missing/doing wrong?

**Comment by arybczak** [comment]
https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html

**Comment by fth86** [comment]
I can confirm this on an Ubuntu 16.04 system. readline-common from the repositories is installed.

**Comment by ecl1ps3** [comment]
> https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
This is installed, and readline-common. Still getting the same error...
