### ISSUE TITLE
play_item only in playlist

### ISSUE THREAD

**Issue by quite** [arybczak/ncmpcpp#177]
I would like to let a press of Enter only do play_item if I'm in the playlist screen. For me, I end up accidentally hitting Enter in the library screen when I'm browsing and entering directories, but then suddenly reach the actual files level... so a new song is added to the bottom of my playlist and it begins to play! Ack.

I know how to use dummy binding, and was able to disable play_item everywhere. But, I'd still like it on the playlist screen.

**Comment by arybczak** [comment]
```
def_key "enter"
  require_screen "playlist"
  play_item
```
Above should do what you want, right?

**Comment by quite** [comment]
Yes! Unfortunately, I hadnot ever read the example bindings very carefully. But now I did, and push_character is interesting...
