### ISSUE TITLE
JumpToPlayingSong in playlist editor

### ISSUE THREAD

**Issue by hghwng** [arybczak/ncmpcpp#178]
It'd be convenient if pressing `o` jumps to the current playing song in the playlist editor. I'd like to implement this feature on my own, but the desired behavior is still in need of discussion.
<br />
<br />It's possible that a track is included in multiple playlists. There are several possible behavior of `JumpToPlayingSong`:
<br />
<br />1. When the `Content` column is active, pressing `o` jumps to the first occurrence in the current playlist if exists.
<br />2. Pressing `o` jumps to the next occurrence in all playlists if exists, whatever the current active column is. In this way, pressing multiple times jumps to the next occurrence of current track in all playlists. This behavior is not consistent with those of other screens, but it's intuitive and useful.
<br />
<br />What's the desired behavior?

**Comment by arybczak** [comment]
I think cycling through all occurrences would be the best option.
