### ISSUE TITLE
macro require playing state (scripting add after currently playing on current playlist)

### ISSUE THREAD

**Issue by quite** [arybczak/ncmpcpp#179]
I just found out about push_characters, and quickly hacked upp what I had wanted for long time, that is... adding after currently playing song on current playlist, but without the menu hassle! As below.
This works OK, but I quickly found one issue -- if nothing is playing, the macro will leave us in the menu. Can we require playing somehow?
```
def_key "A"
  require_runnable "add_selected_items"
  push_characters "a"
  push_character "enter"
  push_character "down"
  push_character "down"
  push_character "enter"
```

**Comment by arybczak** [comment]
Not directly, but I think you can require jump to current song to be runnable?

**Comment by trygveaa** [comment]
Nice, I've wanted a binding for this as well. I tried requiring `jump_to_playing_song`, but that didn't work from the search screen. However, requiring `jump_to_position_in_song` or `seek_forward` seems to work.

**Comment by quite** [comment]
Ah, that worked! Tack.

**Comment by arybczak** [comment]
Related: a5827cf1de3b37aae7294f1f0fed40d3d3431382
