### ISSUE TITLE
Unify the config syntax

### ISSUE THREAD

**Issue by Tsutsukakushi** [arybczak/ncmpcpp#18]
Some things can be bolded and others can't, some colors can be set with 2_5 etc. and others require color names and thus can't have different background color.

Things like columns playlist and volume need bolding from the top of my head.
The playlist also needs to use the new fg_bg notation.

Changing the notation to red_green instead of 2_3 would probably help many people understand it.

**Comment by arybczak** [comment]
This is pretty much done now, see https://github.com/arybczak/ncmpcpp/blob/51d7c9d7d51d79ed039b9f89bd5270f23e7b47e4/doc/config#L497.
