### ISSUE TITLE
Artist Info preferred language doesn't seem to work

### ISSUE THREAD

**Issue by HptmHavoc** [arybczak/ncmpcpp#183]
Hi,

i recognized that the option **"lastfm_preferred_language ="** doesn't seem to have any effect on the language ncmpcpp fetches the artist info in.
I tried different language codes f.e de and fr, with an artist info where i can be sure it exist in this languages (http://www.last.fm/de/music/Anthrax/+wiki).

If i am doing something wrong, please tell me. 

```
$ ncmpcpp --version
ncmpcpp 0.7.7

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info
 - outputs
 - visualizer
 - clock

encoding detection: enabled
built with support for: curl fftw ncurses taglib unicode
```

**Comment by arybczak** [comment]
Fixed by b2f29c67568dd126a5d364fea6ff020f090c271d.
