### ISSUE TITLE
Hang when switching between library two/three column mode

### ISSUE THREAD

**Issue by rnkn** [arybczak/ncmpcpp#186]
When switching between library two/three column mode, ncmpcpp calls the MPD `listallinfo` command. If this command is blacklisted, which it is by default for [Mopidy](https://www.mopidy.com), then ncmpcpp will hang, outputting the following error ad infinitum until killed:
~~~
WARNING  MPD client used blacklisted command: listallinfo
~~~

**Edit:**
~~~
$ ncmpcpp --version
ncmpcpp 0.7.7

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info

encoding detection: enabled
built with support for: curl ncurses taglib unicode
$ mopidy --version
Mopidy 2.1.0
$
~~~

**Comment by arybczak** [comment]
https://docs.mopidy.com/en/latest/ext/mpd/ it looks like you can remove blacklisting of listallinfo in mopidy's configuration. ncmpcpp should handle that error gracefully anyway, I'm just poiting that out if you didn't know.

**Comment by arybczak** [comment]
Does ncmpcpp show any error in its statusbar when this happens?

**Comment by rnkn** [comment]
The status bar shows:
~~~
MPD: "listallinfo" has been disabled in the server
~~~
and then ncmpcpp needs to be killed.

I'm not sure, but I think that listall and listallinfo are blacklisted by mopidy because of Spotify, as in, maybe these commands would try to list everything in the Spotify catalogue? I don't have a Spotify premium account, so I can't test.

**Comment by arybczak** [comment]
Can you connect to mopidy server via netcat (for local connection `netcat localhost 6600`) and paste the output of a command `listallinfo ""`?

**Comment by arybczak** [comment]
Also, please check if 0185ee7fa468f7d8df04a67a879e4ead5f6da28e fixes the problem.

**Comment by rnkn** [comment]
I'm on macOS, there's no netcat. Sorry.

Unfortunately the source does not build on macOS, so I cannot check if that commit helps: https://github.com/arybczak/ncmpcpp/issues/187#issuecomment-275913106

**Comment by rnkn** [comment]
Sorry, yes there is a netcat, it's just called nc.

With `listallinfo` still blacklisted:
~~~
$ nc localhost 6600
OK MPD 0.19.0
listallinfo ""
ACK [0@0] {listallinfo} "listallinfo" has been disabled in the server
~~~

With `listallinfo` removed from blacklist:
~~~
~~~

**Comment by rnkn** [comment]
The plot thickens. I had not tested ncmpcpp with `listallinfo` removed from the blacklist... It still hangs when switching from 3 column to 2 column, even with `listallinfo` or `listall` removed from the blacklist.

After the hang, the Mopidy log shows:
~~~
INFO     New MPD connection from [::ffff:127.0.0.1]:55632
INFO     New MPD connection from [::ffff:127.0.0.1]:55634
INFO     New MPD connection from [::ffff:127.0.0.1]:55636
INFO     New MPD connection from [::ffff:127.0.0.1]:55638
INFO     New MPD connection from [::ffff:127.0.0.1]:55640
INFO     New MPD connection from [::ffff:127.0.0.1]:55646
~~~

**Comment by arybczak** [comment]
> (no output)

Alright, so it's actually better to keep it blacklisted because mopidy incorrectly implements this as a no-op. It should return OK, not give no output, because then libmpdclient chokes on that.

**Comment by arybczak** [comment]
Confiirmed as fixed, closing.

**Comment by rnkn** [comment]
This no longer causes a hang with latest from master. With `listallinfo` blacklisted it does not list anything, with status bar reporting:
~~~
Unable to fetch the data, server refused to process 'listallinfo' command
~~~
and Mopidy's console filling up with:
~~~
WARNING  MPD client used blacklisted command: listallinfo
~~~
as long as ncmpcpp is kept in two-column mode.

However with `listallinfo` not blacklisted, there is a still a hang, with console filling up with:
~~~
INFO     New MPD connection from [::ffff:127.0.0.1]:54758
INFO     New MPD connection from [::ffff:127.0.0.1]:54760
INFO     New MPD connection from [::ffff:127.0.0.1]:54762
~~~
which I think is because of Mopidy's incorrect implementation as you mentioned.
