### ISSUE TITLE
ncmpcpp+mpd: view current queue / implicit playlist?

### ISSUE THREAD

**Issue by jonascj** [arybczak/ncmpcpp#188]
I've recently switched to mpd+ncmpcpp from Guayadeque and there is one thing I can't figure out.

From view **4:Media Library** I select an artist in the left column, then select an album in the mid column and press [Enter]. That causes every track on that album to play, and playback stops when the last track has played.

That has to constitute some form of queue or playlist, at least implicitly. These N tracks must be played, and when played stop playback.

Where do I see that (implicit) queue or playlist?

View **1:Playlist** does have the currently playing item highlighted among ALL tracks in the library, but that list gives the impression that it will continue playing after the last track of current album, i.e. there are more tracks on the list in that view (unless your artist and album are at the very end of lexigraphical sorting, then the list stops after that album obviously).

I've asked on [reddit.com/r/linux](https://www.reddit.com/r/linux/comments/5qh007/ncmpcppmpd_how_to_see_the_current_maybe_implicit/) as well, because I only remembered the github issue page after posting to reddit. I'll post any response from here to that thread as well.

**Comment by arybczak** [comment]
> Where do I see that (implicit) queue or playlist?

The playlist screen is exactly that.

**Comment by jonascj** [comment]
Okay, so this was cleared up for me in #mpd@freenode:

In mpd (music player daemon) what I would call the **queue**, the list of items currently being played before playback stops) was historically called the **playlist* (mpd is from 2003). Just as good a word I suppose. Nowadays mpd terms saved lists of songs for playlists (e.g. "Gym max workout" or "Boardgame night"), and what I would call _queue_ is now called _the queue_.

What ncmpcpp calls a playlist is not necessarily related to what mpd calls a playlist. So I don't know why view **1:Playlist** is called Playlist and not _queue_ which is what I would have expected when I started using it. Maybe because it used to be called playlist in mpd, maybe because of something else.

Now my problem; it seems pressing [Enter] on items in view **4:Media Library** (songs, albums, artists) cause item(s) to be appended to the **mpd queue**, giving me an ever expanding mpd queue, which is what I saw under view **1:Playlist**.

This would be equal to only ever call "mpc add <item>" or "mpc insert <item>", what would also just cause the queue to expand with the items you constantly append, unless you run mpd in **consume mode** where the items are removed after being played.

So the solution to my problem (playing some specific songs as a one-off thing) is to clear the queue, then add them, or run mpd in consume mode if I don't want to clear.

**Comment by jonascj** [comment]
>> Where do I see that (implicit) queue or playlist?

>The playlist screen is exactly that.

It turns out you are right, I was just mislead by the name "Playlist" because mpd call it queue (used to call it playlist). And items are not consumed form the list per default, so I need to clear it before adding.

Could you comment on why view 1 is called Playlist? Is it because of this historical mpd playlist thing, or because you think "Playlist" is the best word for the queue of items playing before playback stops?

**Comment by arybczak** [comment]
> Is it because of this historical mpd playlist thing

That's exactly right.

**Comment by jonascj** [comment]
Would you consider renaming it now that it is called queue instead?
https://www.musicpd.org/doc/user/queue.html

**Comment by arybczak** [comment]
No - that requires too many changes for no worthwhile gain. Note that configuration and bindings reference playlist related stuff in several places, so changing the name of the screen without changing them will just create confusion, whereas renaming/deprecating them is even worse.

**Comment by jonascj** [comment]
Yeah, I took at look at the source, and it will take some effort to change all references to PlaylistSomething to QueueSomething, and the gain is minimal, agreed.

Thanks for discussing this, closing.
