### ISSUE TITLE
Mouse scrolls full page instead of `lines_scrolled` setting

### ISSUE THREAD

**Issue by olmokramer** [arybczak/ncmpcpp#189]
No matter what I set the `lines_scrolled` setting to, whenever I scroll with my mouse ncmpcpp still scrolls an entire page down. I'd be glad to provide some logs if you need them, just don't know which ones :)

**Comment by onodera-punpun** [comment]
Info about what terminal you use and such would be helpful I think.

**Comment by olmokramer** [comment]
Ha of course! And thanks for the quick reply! I use urxvt. You can find my configs [here](https://github.com/olmokramer/.dotfiles), in particular:
* [ncmpcpp config](https://github.com/olmokramer/.dotfiles/tree/master/mpd/.config/ncmpcpp)
* [mpd config](https://github.com/olmokramer/.dotfiles/blob/master/mpd/.config/mpd/mpd.conf)
* [urxvt Xresources](https://github.com/olmokramer/.dotfiles/blob/master/urxvt/.Xresources.d/urxvt)

**Comment by arybczak** [comment]
You need `mouse_list_scroll_whole_page = no`.

**Comment by olmokramer** [comment]
Fair enough... Works as expected now. Thanks!!!
