### ISSUE TITLE
configure.ac problems with debian / ubuntu

### ISSUE THREAD

**Issue by ryanfantus** [arybczak/ncmpcpp#19]
Boost libs in deb/ubuntu no longer have the `-mt` suffix. To make autogen.sh complete without error, I had to remove the following:
`AS_IF([test -z "${BOOST_LIB_SUFFIX+x}"], [BOOST_LIB_SUFFIX=-mt])
AC_ARG_VAR([BOOST_LIB_SUFFIX], [Boost library name suffix [default=-mt]])`
Perhaps there's a way to test for either (with or without suffix)?

**Comment by kchr** [comment]
Why is this not default behavior? Separate multithread packages must be a fringe case today...

Debian and Ubuntu are two of the most popular active distributions. Both of them dropped all -mt suffixes years ago.

**Comment by arybczak** [comment]
E.g. Gentoo uses that prefix.

**Comment by cweiske** [comment]
The following stackoverflow answer suggests:
> The proper fix is to convert the script to use the Boost macros from the Autoconf Archive.

http://stackoverflow.com/a/25224508/282601

The error I got on Ubuntu 14.04 was:

    checking for boost/filesystem.hpp... yes
    checking for main in -lboost_filesystem-mt... no
    configure: error: no boost.filesystem library found

**Comment by arybczak** [comment]
That answer is wrong in that configure.ac doesn't accept empty value of BOOST_LIB_SUFFIX. It does. I can't add a comment pointing it out though as I don't have enough reputation (yay stackoverflow).

Suggestion of using autoconf macros instead is sound though.

**Comment by musamanyama** [comment]
I'm sorry, but i think I am still lost with this conversation. 
Please clarify this for me where do I add this line? 
```
$ BOOST_LIB_SUFFIX="" ./autogen.sh.
```
I tried deleting the lines, didn't work, then tried putting that line instead of 

```
AS_IF([test -z "${BOOST_LIB_SUFFIX+x}"], [BOOST_LIB_SUFFIX="" ./autogen.sh) AC_ARG_VAR([BOOST_LIB_SUFFIX], [Boost library name suffix [default=-mt]])
```
As you can see, but that didn't work either. Please explain a bit.

**Comment by arybczak** [comment]
BOOST_LIB_SUFFIX now defaults to empty string, so explicitly setting it is not needed.

**Comment by musamanyama** [comment]
Aah.. Sure! I don't know what branch I was in (0.6.x) but it's the result of my folder mess, but after looking at your (0.7.x) branch then master branch configure.ac code I fully understood and re-cloned your repo. It's working now. Thank You. :-)
