### ISSUE TITLE
Search does not work if song changes right before pressing enter

### ISSUE THREAD

**Issue by nonamethanks** [arybczak/ncmpcpp#190]
Steps:
1. Go to 10 seconds before a song ends
2. Search for something without pressing enter
3. Once the song has changed, press enter
The search won't work unless the string is modified, for example deleting and retyping the last character.

Using freshly cloned master.

**Comment by arybczak** [comment]
What do you mean by search?

**Comment by nonamethanks** [comment]
I mean press / and write whatever you want to search in the "Find forward:" prompt.

**Comment by arybczak** [comment]
Ok. What do you mean by "search won't work"?

**Comment by nonamethanks** [comment]
I mean that if I search for "Dongs" and wait for the currently playing "Test Song1" to change to "Test Song2" before I press <Enter>, the selected song will still be "Test Song2" rather than the first occurrence of "Dongs", which would instead be the normal behavior of the program had I pressed <Enter> *before* the song changed.

**Comment by arybczak** [comment]
Do you have `autocenter_mode = yes` in your config file?

**Comment by nonamethanks** [comment]
Both "autocenter mode" and "centered cursor" are set to "yes".

**Comment by arybczak** [comment]
Ok, so it just repositions the cursor because that's what it's supposed to do. You can manually reposition after you're done with searching by jumping to next found item ("." by default).

**Comment by nonamethanks** [comment]
Well yeah, that workaround works, but additional keystrokes because of an uncaught exception is hardly a feature. The documentation says "Find item forward", not "Find item forward unless the song changed".

**Comment by arybczak** [comment]
Fixed by 0033bc3431e8d3b7a67dc62a1f87d31a1130d65a.
