### ISSUE TITLE
First press of seek forward/backward key "jumps" to current time

### ISSUE THREAD

**Issue by danadam** [arybczak/ncmpcpp#191]
I have ``seek_time`` set to 10. When I press ``f`` or ``b`` key there is a pause in playing the music for a fraction of a second and then it continues to play from the same position. Only when I double press the key fast enough it skips the intended 10 seconds.

**Comment by arybczak** [comment]
Fixed by 05bf53d0abda580039445e1e69fe066a3446a4fd.
