### ISSUE TITLE
[Suggestion] Media library sort: If album artist tag is empty, sort by artist

### ISSUE THREAD

**Issue by sunox1** [arybczak/ncmpcpp#192]
Hello,

Until last week I was using an older version of ncmpcpp (the one in the Debian Jessie repos), which did album artist sorting a little bit differently. By default, when you selected 'album artist' as the primary media library sorting tag, it sorted by album artist primarily, and secondarily by artist (if album artist field was empty). In the version I'm using now (0.7.4) it sorts only by album artist, and places all albums with an empty album artist tag in <empty>. I tried setting an option called 'media_library_secondary_tag' in the config, but ncmpcpp wouldn't launch afterwards.

Would it be possible to get this feature back? Alternatively, is there a workaround I can use? I have a ton of albums without this tag, and it would be really nice if I could avoid going setting this tag for all albums. 

Thanks for reading.

**Comment by arybczak** [comment]
You can use https://github.com/arybczak/ncmpcpp/tree/master/extras - it copies artist to album artist for songs that do not have it.

**Comment by sunox1** [comment]
Well that's pretty handy! Thanks - and thank you for ncmpcpp as well. 

Cheers.
