### ISSUE TITLE
Binding for "start playing playlist"

### ISSUE THREAD

**Issue by kalj** [arybczak/ncmpcpp#197]
Previously, "p" toggled the play/pause state, even if it was in stopped state previously. Now it seems that has changed. If the state is stopped, there seem to no longer be any keybinding for starting playing current playlist from the start, except opening the playlist view and pressing enter on the first track. Am I missing something, or why was this functionality dropped?

**Comment by kalj** [comment]
Or is this related to changes in libmpdclient?

**Comment by arybczak** [comment]
> Previously, "p" toggled the play/pause state, even if it was in stopped state previously

I never observed that, but if such behavior was there and is not anymore, it's due to how MPD handles these commands.
