### ISSUE TITLE
Database update doesn't detect removed files

### ISSUE THREAD

**Issue by lamons** [arybczak/ncmpcpp#205]
When I execute update command ("U"), it shows "Database update finished" but the deleted tracks didn't be removed from the database. Sometimes the newly added files also didn't appear. 

I checked the log file and found this:

`Apr 02 10:33 : exception: Failed to access /.../Xela & Greg Haines & Danny Saul/The 12th Chapel/01 The 12th Chapel [vinyl rip].m4a: No such file or directory`
`Apr 02 10:37 : exception: Failed to decode /.../Sonicbrat/Murmurations/10 niǎo (Bonus Track).wav`

This appears in the log every time I tried to update the database. 
Looks like the program can't access the deleted files then stopped, so the added files also didn't be detected.

**Comment by arybczak** [comment]
This is related to MPD, not ncmpcpp. Apparently MPD can't finish the update for some reason (possibl related to what is in the log).
