### ISSUE TITLE
I cannot decrease volume with "left" or "-" key

### ISSUE THREAD

**Issue by TheIdealis** [arybczak/ncmpcpp#207]
I can increase the volume with "right" or "+", but I cannot decrease it with "left" or "-". I've tried version 0.8_dev and 0.7.7 and multiple terminal emulators.

**Comment by TonCherAmi** [comment]
I have this problem as well. I believe it to be an MPD issue though, because for example 
`mpc volume -2` with `volume:100%` does not change the volume at all and `mpc volume -3` yields `volume:98%`. So it might make sense to change the default value of `volume_change_step` until its fixed. My MPD version is 0.20.6, by the way.

**Comment by arybczak** [comment]
Yes, that is a regression in MPD since 0.20. Good luck explaining that to the MPD developer though - he recently banned me from the tracker and IRC channel because of https://bugs.musicpd.org/view.php?id=4651.

**Comment by onodera-punpun** [comment]
Well that's stupid, I'm pretty sure ncmpcpp is the reason about 50% of the people use mpd.

**Comment by TheReverend403** [comment]
@arybczak >he recently banned me from the tracker and IRC channel because of https://bugs.musicpd.org/view.php?id=4651.

I'm not surprised with that immediate hostile attitude.

> it's just sad that others will have to endure your stupid decision. 
>I should've known better that to try reason with you

**Comment by onodera-punpun** [comment]
While rude, banning the dev of a prominent program that uses your program from your *bugtracker and irc* might be a bit much.

**Comment by TheReverend403** [comment]
Nah, he was being a prick about it, I'd have banned people for less tbh.

**Comment by arybczak** [comment]
@TheReverend403 alright.

In any case, if anyone wants to file a bug on mantis about the regression, you are welcome to.

**Comment by edio** [comment]
I opened an issue, and there's an explanation from developer why it happens
https://github.com/MusicPlayerDaemon/MPD/issues/104#issuecomment-325666186
