### ISSUE TITLE
Display of unicode chars

### ISSUE THREAD

**Issue by vanishing** [arybczak/ncmpcpp#21]
Recently, not sure which commit, I found ncmpcpp displays unicode chars weirdly....
Like so: 
![recorded](https://cloud.githubusercontent.com/assets/3933077/5601213/c38338d8-92c0-11e4-8121-e11a2d79921e.gif)

**Comment by arybczak** [comment]
Does this happen with the current master? I know there was a bug like this, but I thought I fixed it.

**Comment by vanishing** [comment]
Yes, this happens with the current master.
However, if I comment out the Reload part of update function in lyrics.cpp, this does not happen:
void Lyrics::update()
{
#	ifdef HAVE_CURL_CURL_H
	if (isReadyToTake)
		Take();
	
	if (isDownloadInProgress)
	{
		w.flush();
		w.refresh();
	}
#	endif // HAVE_CURL_CURL_H
	/* if (Reload)
	{
		drawHeader();
		itsScrollBegin = 0;
		Load();
		Reload = 0;
	}*/
}
What's weird is not only lyrics are doing this, but also the tags, however comment out the Reload part "fixes" them all.,,

**Comment by arybczak** [comment]
Can you give me the file with these lyrics? Also, does this happen only in lyrics screen or also in song info/artist info?

**Comment by arybczak** [comment]
Also, does this happen in all of your terminal emulators or only a specific one? If so, which one?

**Comment by vanishing** [comment]
Sorry for replying late.
This happens in all my terminals, and this happens both in lyrics and tag editor, but not in playlists.
For the file with lyrics, it is easy to produce, you can find any mp3 file, rename it to a.mp3. Then create a.lrc with content"测试", play the file and check the lyrics.

**Comment by arybczak** [comment]
I don't get it. Check the lyrics with what?

**Comment by vanishing** [comment]
Sure, the lyrics is at: http://paste.ubuntu.com/9859478/
The artist is: 周杰伦, or Jay Chou
The title is: 七里香

I think you can download it here: https://www.mp3days.net/download-songs/i_1K-LFOPi8/%E5%91%A8%E6%9D%B0%E4%BC%A6-%E4%B8%83%E9%87%8C%E9%A6%99-s.html
Click on "Download: 周杰伦 - 七里香 [LYRICS].mp3".

**Comment by arybczak** [comment]
This is rather puzzling, because it doesn't happen here. What version of ncurses do you use?

can you try if this patch http://pastebin.com/fbwzhsD2 fixes the issue?

**Comment by vanishing** [comment]
I can confirm the patch seems to fix the issue.

**Comment by arybczak** [comment]
What ncurses version do you use?

**Comment by vanishing** [comment]
I've got:
```
»»»  apt-cache policy libncurses5
libncurses5:
  Installed: 5.9+20140712-2ubuntu1
  Candidate: 5.9+20140712-2ubuntu1
  Version table:
 *** 5.9+20140712-2ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ vivid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by arybczak** [comment]
Fixed.
