### ISSUE TITLE
Suggestion: friendler application name: nincompoop

### ISSUE THREAD

**Issue by axelsimon** [arybczak/ncmpcpp#213]
Hi,
I've discovered ncmpcpp, which looks great.

The name, however, is unpronounceable and super cryptic.
If this is completely done on purpose (which, understandably, can be fun too), then by all means please ignore this issue.

However, if you are interested, I suggest the name [nincompoop](https://en.wiktionary.org/wiki/nincompoop). It's a funny word, close to ncmpcpp and it sounds pretty good.

Just a suggestion, I hope it's useful :)

**Comment by onodera-punpun** [comment]
en see em pee see pee pee

**Comment by arybczak** [comment]
I can't argue that ncmpcpp is a good name (because it's not), but if I was to change it, it would be cmpc. I don't see why you'd change it to something longer.

**Comment by axelsimon** [comment]
To answer that, longer can be interesting if it's easier to pronounce or remember, the human brain remembers words (even obscure) better than pseudo-random strings of letters. Oh and longer words are not really an issue on the CLI given we have auto-completion in the vast majority of cases. But anyway, thanks in any case for making ncmpcpp.

**Comment by mmuman** [comment]
Just make a [song about it](https://www.youtube.com/watch?v=ab8GtuPdrUQ)… and people will remember :D
