### ISSUE TITLE
[Feature Request] Allow setting default state of modes

### ISSUE THREAD

**Issue by rieje** [arybczak/ncmpcpp#214]
This is a feature request--allow setting the default state of modes like repeat, random, consume, etc.

Every time I start ncmpcpp I always toggle repeat mode to on, for example.

**Comment by onodera-punpun** [comment]
You could alias ncmpcpp to `mpc random && ncmpcpp` or something like that as well?

**Comment by arybczak** [comment]
Mpd is able to save state between runs, so you need to configure it to do that.
