### ISSUE TITLE
[CRASH] colors_enabled = no

### ISSUE THREAD

**Issue by roguepointer** [arybczak/ncmpcpp#218]
ncmpcpp 0.8 seems to be crashing when colors_enabled = no
I've tried an empty config with only colors_enabled = no, and it crashed with: Floating point exception. colors_enabled = yes, doesn't result in any crash.

>       colors_enabled = yes/no
>               No need to describe it, huh?
nah.

Core dump:
[coredump.zip](https://github.com/arybczak/ncmpcpp/files/1053076/coredump.zip)

**Comment by hghwng** [comment]
Reproduced on my machine.

**Comment by hghwng** [comment]
@roguepointer I've submitted the pull request that solves this bug. I'm not sure whether my solution is the desired one from the owner's perspective.

See #223

**Comment by arybczak** [comment]
Fixed by a22cd2c68c71481c653d9f6547f2e7b46ce57106.
