### ISSUE TITLE
Odd search constraint history behaviour

### ISSUE THREAD

**Issue by ayekat** [arybczak/ncmpcpp#222]
As noted in #221, whenever the user hits `/` for searching, the previous search constraint is copied and left to the user to edit. A slightly unintuitive consequence of that is that we need to hit `Up` (or `Ctrl`+`P`) twice in order to get to the previous constraint.

It is also possible to edit the history, but here I found some oddity. Imagine a history with the following 3 constraints:

    A   ← oldest
    B
    C   ← newest

Now I hit `/` (implictly creating a copy of `C`), scroll up to `A`, change it to `Foo`, then scroll back down to another entry (say `C`) and hit `Enter` there, the history will look as follows:

    Foo
    B
    C
    C

Now here is the peculiarity: If I hit `/` again and scroll up to `Foo`, change it to `Bar`, then—*without scrolling away*—hit `Enter` there, the history will look as follows:

    A
    B
    C
    C
    Bar

As expected, `Bar` has been appended to the history, but for some reason, `Foo` changed back to `A` (and not to `Bar`). There is certainly some logic behind it, but I find it pretty unintuitive. Is there an explanation for this?

**Comment by seeegma** [comment]
There is a bigger problem here: included in the history are the names of newly-created playlists.

**Comment by arybczak** [comment]
@ayekat History is managed by readline, I'm not sure what the exact logic behind modifying it is.

@seeegma How is that a problem?

**Comment by seeegma** [comment]
@arybczak It would only be an inconvenience. When would you want to search your library for the name of a playlist you created? The histories should be separate, if anything.

**Comment by arybczak** [comment]
As I mentioned, there is only one history and it's managed by readline, just as in shell etc.
