### ISSUE TITLE
Installing latest version on mac

### ISSUE THREAD

**Issue by piotryordanov** [arybczak/ncmpcpp#224]
The `brew` version of ncmpcpp is `0.7.7_2`.
I downloaded the latest version from `http://rybczak.net/ncmpcpp/stable/ncmpcpp-0.8.tar.bz2` and ran `./configure` but it broke with the error:
`configure: error: ncursesw is required!`

I do have ncurses installed from homebrew, but I'm not sure if that's enough. 

Any idea what I should do?

Thank you :)

**Comment by arybczak** [comment]
https://github.com/arybczak/ncmpcpp/issues/187#issuecomment-289713975 should help, some else had the same problem.

**Comment by Hamuko** [comment]
The Homebrew formula [has been updated to 0.8](https://github.com/Homebrew/homebrew-core/pull/14421), so you should probably just install it through Homebrew. And if the formula is at some point lagging behind, you can just install the latest git master using `homebrew install --HEAD ncmpcpp`.

I suggest closing down this issue.

**Comment by piotryordanov** [comment]
indeed it was updated to 0.8. Thank you @Hamuko !
