### ISSUE TITLE
Delete previous filter when applying a new one

### ISSUE THREAD

**Issue by GhostValk** [arybczak/ncmpcpp#228]
When i apply a filter to the playlist, if there was a previous one, i have to manually delete that one from the input line before typing the new one. ¿Is there any way to make ncmpcpp delete the current filter automatically when the filter key is pressed?

An example.. let's say i do "Apply Filter: Author_1" If then i want to change the filter, when i press the binded apply filter key, it shows the active filter -> "Apply Filter: Author_1" and i have to manually delete it, i would like to show the input line empty "Apply Filter:" as if they weren't one for an easy and fast usage.

**Comment by seeegma** [comment]
this was added as a feature. see [here](https://github.com/arybczak/ncmpcpp/issues/221)

**Comment by GhostValk** [comment]
Thanks, but already figured out how to do it; made a little macro for my filter-binding to leave it as this:

def_key "g"
  push_character "ctrl-u"
  apply_filter

Now it works as expected =)

**Comment by arybczak** [comment]
Fixed by fa9838efb28cb17a81a6dde07d91233a2260c4f5
