### ISSUE TITLE
song_window_title_format won't accept a simple string

### ISSUE THREAD

**Issue by mikerodrigues** [arybczak/ncmpcpp#23]
I used to have this in my config:

    song_window_title_format = "ncmpcpp"

This would set the window title to just "ncmpcpp" in 0.5.6.

I upgrade to version 0.6.1 and now the window title is empty. If I add something like:

    song_window_title_format = {%a ncmpcpp}

I see the "ncmpcpp" string, but I don't want to have to include variables.

This doesn't work either:

    song_window_title_format = {ncmpcpp}

**Comment by arybczak** [comment]
0.5.6 is 4 years old, so I have no idea what changed until 0.6.1 that affected that. Version from master (0.7_pre) had the whole format mechanism rewritten though and your case works properly there, so you may want to try it or wait for the release, depending if it's a pressing issue for you.
