### ISSUE TITLE
Cannot compile ncmpcpp [Cannot find Boost headers version >= 1.60.0]

### ISSUE THREAD

**Issue by ecl1ps3** [arybczak/ncmpcpp#232]
When i run ./configure i get this message:
`checking for Boost headers version >= 1.60.0... no`
`configure: error: cannot find Boost headers version >= 1.60.0`

I've installed the most recent boost libraries using `sudo apt-get install libboost-all-dev`

Edit: I've managed to get boost working, but now i'm running into other problems. I'll close this case and open a new one.

**Comment by ayekat** [comment]
> I've installed the most recent boost libraries using `sudo apt-get install libboost-all-dev`

Which distribution version are you using? Boost >= 1.60 is packaged [starting with Ubuntu 16.10][1] (*Yakkety Yak*) and [starting with Debian 9][2] (*Stretch*).

If you want to check which version of boost is really installed on your machine, have a look at the `BOOST_VERSION` macro definition in `/usr/include/boost/version.hpp`.

[1]: https://packages.ubuntu.com/yakkety/libboost-all-dev
[2]: https://packages.debian.org/stretch/libboost-all-dev

**Comment by ecl1ps3** [comment]
I am currently using Raspbian 8.0, "Jessie".
The boost version i'm currently using is noted as 1.55.
I've tried to manually compile a 1.6x version, but apparently that has failed.
