### ISSUE TITLE
Bottom line separator is not rendered when switch to alternative interface and back

### ISSUE THREAD

**Issue by cglogic** [arybczak/ncmpcpp#235]
Step 1, run ncmpcpp:
![screenshot-2017 07 27-10 24 09](https://user-images.githubusercontent.com/14204812/28659003-76e9a448-72b6-11e7-9dc3-5a651fb60ad4.png)

Step 2, switch to alternative user interface:
![screenshot-2017 07 27-10 24 12](https://user-images.githubusercontent.com/14204812/28659006-76f1cf6a-72b6-11e7-94d3-01f70f38c995.png)

Step 3: then switch back to classic:
![screenshot-2017 07 27-10 24 17](https://user-images.githubusercontent.com/14204812/28659004-76eda200-72b6-11e7-9d10-641d47d2518a.png)

Step 4, wait while tooltip is hide:
![screenshot-2017 07 27-10 24 20](https://user-images.githubusercontent.com/14204812/28659005-76ef5906-72b6-11e7-8d51-d11be714815f.png)

Ncmpcpp must is not play audio at this time.

**Comment by arybczak** [comment]
Fixed via 51fe8dc2c88610fad0a15f64709fde515300be6c
