### ISSUE TITLE
Ncmpcpp exits with error "Floating point exception (core dumped)" when colors_enabled = no

### ISSUE THREAD

**Issue by augustus-rex** [arybczak/ncmpcpp#241]
When I have the option `colors_enabled` set to `no` in the config file ncmpcpp won't start and I get this error message printed to the console whenever I try to start it: `Floating point exception (core dumped)`.

I have solarized light as my terminal color scheme and when I run ncmpcpp with colors enabled the color of the song titles are so light they are barely readable, and I haven't found a way to change the color of the song title. That is why I prefer to run ncmpcpp with colors disabled.

**Comment by tansly** [comment]
I could reproduce the problem and traced it with gdb. The exception occurs on src/curses/window.cpp line 223:
`result = (background() + 1) % COLORS;`
The COLORS (I guess it is something exported by ncurses, sorry I'm not familiar with it) equals 0, hence the FPE.

**Comment by tansly** [comment]
Just noticed it has already been fixed in 0.8.x branch with commit a22cd2c.

**Comment by augustus-rex** [comment]
Oooh, looksy there. Stupid of me to not check that before I opened the issue. But thanks for your help nonetheless :)

**Comment by arybczak** [comment]
Color of a song title can be changed with song_list_format or song_columns_list_format.
