### ISSUE TITLE
The comment to an mp3 file is incorrectly read

### ISSUE THREAD

**Issue by grdw** [arybczak/ncmpcpp#247]
Version: ncmpcpp 0.7.4

If I edit a comment:

<img width="254" alt="screen shot 2017-09-05 at 15 07 49" src="https://user-images.githubusercontent.com/2676542/30062593-03b6f3ee-924c-11e7-8ec9-243b7b0a9160.png">

And try to save it.

The comment is actually there:

<img width="587" alt="screen shot 2017-09-05 at 15 08 42" src="https://user-images.githubusercontent.com/2676542/30062637-2f0a811e-924c-11e7-861a-3117efe67483.png">

But if I want to edit again, the comment in the edit screen is gone:

<img width="267" alt="screen shot 2017-09-05 at 15 07 13 1" src="https://user-images.githubusercontent.com/2676542/30062651-3736ffd4-924c-11e7-98a5-c59416771f1f.png">

**Comment by foxdevilwild** [comment]
@grdw By default mpd doesn't include comment metadata, so while the tags get written correctly they never make their way to the database (and then back to your client).

Add this to your mpd.conf and then re-create (not just update) mpd's database:
`metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,comment,disc"`
