### ISSUE TITLE
--current-song doesnot work

### ISSUE THREAD

**Issue by moeinroid** [arybczak/ncmpcpp#249]
Hi
ncmpcpp version: 0.7.4
mpd version: 0.20.9
OS: Debian Sid

I use this command:
`ncmpcpp --current-song "%a - %t (%b)" 2>/dev/null`
but it doesnot work with given format and it's same all the time
even this:
`ncmpcpp --current-song "%a" 2>/dev/null`
again it shows default pattern!

**Comment by tansly** [comment]
It works if you do `ncmpcpp --current-song="%a" 2>/dev/null`, note the `=`. However, the ncmpcpp manpage does not indicate anything about this, and boost's program options library requires that `=` AFAIK. I think the relevant section in the manpage could be changed as `--current-song=FORMAT` to resolve this ambiguity. Most GNU command line tools (check `man ls`, `man sed` for examples), even though they support arguments to long options without the `=`, document the usage with `=` in the manpages, so I think this is a reasonable approach.

**Comment by arybczak** [comment]
Fixed in 0.8.1_dev.
