### ISSUE TITLE
Incremental database search

### ISSUE THREAD

**Issue by IvanMalison** [arybczak/ncmpcpp#25]
Is there a technical reason for which this does not exist?

**Comment by arybczak** [comment]
I don't know what it is. Can you elaborate?

**Comment by IvanMalison** [comment]
Yeah, I just mean like search that shows you results as you type.

**Comment by arybczak** [comment]
That would fetch large parts of the database multiple times, which is rather slow for big databases.

**Comment by IvanMalison** [comment]
Sure. Couldn't you add an incremental search but leave the existing search as is? Are you philosohpically opposed to something like this. I made something that connects to mopidy (while using the mopidy-spotify backend) in emacs (using helm), and it seems to perform well enough. Obviously, much of the work is being offloaded to the spotify servers in this case.

Is there no way to ask about how many results are going to be returned from a search query in the mpd protocol. You could only start displaying results once a certain threshold is reached...

**Comment by arybczak** [comment]
> Are you philosohpically opposed to something like this

Not really. Although I have no idea how it could look in the UI. If you do, share the idea please.

> If you wanted to be really smart about it, you could fetch the results at the threshold and then do the rest of the filtering inside of ncmpcpp

Yeah, in theory you can fetch the whole database first and then filter it locally, but that creates caching problems (not very big, but still).

**Comment by IvanMalison** [comment]
I kind of imagine it looking a lot like this existing search. It would just narrow further if you type more

**Comment by untitaker** [comment]
I think the only performant way to implement this feature is to load mpd's whole database into RAM and do the searching on the clientside. The actual matching could be taken over by e.g. [fzf](https://github.com/junegunn/fzf).

**Comment by arybczak** [comment]
Yeah, and that's the problem. See http://www.musicpd.org/doc/protocol/database.html, the description of listallinfo. It's explicitly advocated against keeping the copy of the database (now, to be fair, ncmpcpp actually does use this command while sorting by mtime in media library or searching in the database with regular expressions, but it doesn't actually loads it into memory all at once, just streams it from the server and processes it into something it needs, it doesn't leave it verbatim in memory).

Therefore I don't think it's a good idea to implement this.

**Comment by untitaker** [comment]
You *can* stream into fzf and still allow the user to type immediately, so you don't actually have to *save* the database though.

**Comment by arybczak** [comment]
I would also need to be convinced, why this feature is so interesting. Why is regular search not necessary and you need incremental? I'm not opposed to adding fuzzy search variant to search engine (as long as there are any usable libraries for that in C++), but incremental seems like a lot of work for a tiny amount of gain.

**Comment by untitaker** [comment]
>I'm not opposed to adding fuzzy search variant to search engine (as long as there are any usable libraries for that in C++)

I guess the broader feature request (from my side, at least) would be to hook custom search interfaces into ncmpcpp, e.g. be able to tell ncmpcpp to pipe all songs into a custom binary.

But I agree that this is not really needed -- I currently use a script that hooks mpc and fzf together to quickly add songs, and it works well enough.

**Comment by teto** [comment]
I've been on #mpd to ask for support in the protocol to this. The answer was "show me the bottleneck" and apparently rather than fetching the whole database, it looks easier and fast enough to just send a new search (for instance on my SSD  `$time mpc search any "" ` => 0,00s user 0,00s system 9% cpu 0,043 total).
As for what it looks, check https://github.com/junegunn/fzf, i.e. it means you don't have to press "Search" to get the results, just launch a new query for every typed character.

Note: With this approach, fuzzy search is not possible.

**Comment by IvanMalison** [comment]
@arybczak If you mess up your search, or want to try several different searches, it is currently quite annoying to have to go back and press buttons to reexecute the search. Also, being able to successively narrow by applying different filters (i.e. by artist and then by album) would be quite useful.

there is a reason that this is a feature in nearly every search engine/music streaming service out there...

**Comment by arybczak** [comment]
Ok, I'm convinced that this can indeed be useful, reopening.

@teto I have ~6000 songs in the database and it takes 100ms for me. This is a visible delay. Still not that much (and it can start searching after e.g. 3 characters were output, which mitigates the issue a little), but consider that the delay will be much bigger while searching in a remote database. The search could be started asynchronously, but that opens whole another can of worms. Alternatively the "incrementality" of the search could be optional.

**Comment by untitaker** [comment]
FWIW, this is the script I'm using to quickly add a song to the playlist:

    #!/bin/sh
    set -e
    set -o pipefail

    song="$(mpc search any '' | fzf)"
    mpc insert "$song"

I have 10k tracks and a local mpd. The mpc search takes slightly less than 100ms (checked with `perf stat -r 10 mpc search ''`), but I can instantly start typing.

I think it's not easy to say that avoiding/using

**Comment by teto** [comment]
I understand this is suboptimal but mpd guys made it clear that without some figures/usecases they wouldn't investigate this further.
So I believe resending requests is an accessible first step. This will be enough for me on my SSD and small database (I will try without the SSD) and will provide some figures for mpd guys, in case they wish to investigate further. I don't know what would be the best way to implement this, I guess some kind of transaction mechanism.
Starting the search after 3 characters looks like a good mitigation measure as well as making it optional. It could also wait X ms without any new typed characters before relaunching a request.

**Comment by arybczak** [comment]
@teto What does "investigating further" means?

**Comment by teto** [comment]
As you mentioned there are cases where sending a new request may not be fast enough and downloading the whole db might be out of question. 
I don't know incremental live search is usually implemented ? My guess is that starting some threshold, the results are cached by the clients and the client filters them but there may be other schemes requiring some support on the server side (some kind of transaction mechanism).
I don't use spotify but I would be interested in knowing how they do it.

**Comment by larson-carter** [comment]
I'm going to close this issue for right now. I will investigate later if someone reopens this and or updates this issue.
