### ISSUE TITLE
Playlist/status shows wrong song playing

### ISSUE THREAD

**Issue by Phrogz** [arybczak/ncmpcpp#256]
I have ncmpcpp/mpd playing a playlist in "consume" mode. Frequently (multiple times per day) the ncmpcpp playlist will fail to consume a song and show incorrect information for the currently playing song.

For example, say I have a playlist with songs A/B/C/D/E/F queued up.
1. A finishes playing. ncmpcpp removes it from the list, showing B/C/D/E/F in the playlist, with "B" playing. _(correct)_
2. B finishes playing. ncmpcpp removes it from the list, showing C/D/E/F in the playlist, with "C" playing.  _(correct)_
3. C finishes playing. ncmpcpp forgets to remove it from the list, showing C/D/E/F in the playlist, with "C" playing...but D is actually playing (heard on the speakers, and seen via `mpc status`.
4. D finishes playing. ncmpcpp forgets to remove it from the list, showing C/D/E/F in the playlist, with "C" playing...but E is actually playing (heard on the speakers, and seen via `mpc status`).

Switching between ncmpcpp views does not fix the problem. I have to quit and restart ncmpcpp to get it properly synchronized again.

```
gkistner@music:~$ ncmpcpp --version
ncmpcpp 0.7

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info
 - outputs
 - visualizer
 - clock

encoding detection: enabled
built with support for: curl fftw ncurses taglib unicode
```
```
gkistner@music:~$ uname -a
Linux music 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
gkistner@music:~$ mpd --version
Music Player Daemon 0.20.4

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa roar ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file alsa archive curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa://

Other features:
 avahi epoll icu inotify ipv6 systemd tcp un
```

**Comment by arybczak** [comment]
You run outdated version of ncmpcpp. Try the latest one (0.8).

**Comment by Phrogz** [comment]
Thank you. I am now in the process of installing all the dependencies needed to build from source, since I can't find a PPA with 0.8 on it for Xenial. I did look through the NEWS and did not see any fixed bugs after 0.7 that seem to apply to this problem. I will re-open this issue if I get 0.8 installed and experience the same issue again.

**Comment by arybczak** [comment]
It's this one: `Fixed an issue that could cause some MPD events to be missed.`

**Comment by Phrogz** [comment]
> _It's this one: Fixed an issue that could cause some MPD events to be missed._

Nice! Thanks.

**Comment by Phrogz** [comment]
Well, I give up. I spent a couple hours figuring out how to build and install boost 1.60 from sources, but ran into #237
