### ISSUE TITLE
undefined reference to symbol 'inflateEnd'

### ISSUE THREAD

**Issue by MasterTextman** [arybczak/ncmpcpp#257]
I tried to build ncmpcpp from the github source, and it kind of worked. However, I noticed that the visualiser and the tag editor weren't there, so I installed the appropriate packages.

After that point, I tried ./configure again and it worked perfectly. However, when I tried to run make...

`/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so: undefined reference to symbol 'inflateEnd'`

This error popped up. At that point, make failed.

I installed zlib in many different ways, as a package, by building it from a tar, but whenever I ran the command `curl-config --libs` , -lz didn't appear. Nothing worked, and now I'm stuck at this stage.

**Comment by arybczak** [comment]
Run configure using `LDFLAGS="-lz" ./configure ...`

12.10.2017 20:19 "MasterTextman" <notifications@github.com> napisał(a):

**Comment by MasterTextman** [comment]
I ran configure like this:
`LDFLAGS="-lz" ./configure --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock`

But the same error popped up unfortunately.

**Comment by MasterTextman** [comment]
`ldconfig -p | grep libz` returns this:
`libzzipwrap-0.so.13 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzzipwrap-0.so.13
	libzzipmmapped-0.so.13 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzzipmmapped-0.so.13
	libzzipfseeko-0.so.13 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzzipfseeko-0.so.13
	libzzip-0.so.13 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzzip-0.so.13
	libzvbi.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi.so.0
	libzvbi-chains.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi-chains.so.0
	libzmq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.5
	libzip.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzip.so.4
	libzephyr.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzephyr.so.4
	libzeitgeist-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0
	libzbar.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzbar.so.0
	libzapojit-0.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzapojit-0.0.so.0
	libz.so.1 (libc6,x86-64) => /usr/local/lib/libz.so.1
	libz.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz.so.1
	libz.so.1 (libc6) => /lib/i386-linux-gnu/libz.so.1
	libz.so (libc6,x86-64) => /usr/local/lib/libz.so
	libz.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libz.so`

**Comment by MasterTextman** [comment]
corin.eu's comments from https://github.com/arybczak/ncmpcpp/issues/138 , specifically the one with the patching and how to rebuild configure helped out and now the program builds properly - however I still have a problem with the tagging.

whenever I try to add the album tag, it says "no such file or directory", even though the directory that I specified in the config is correct.
