### ISSUE TITLE
Segmentation fault when using the --quiet/-q option

### ISSUE THREAD

**Issue by julius383** [arybczak/ncmpcpp#258]
Hi, every time I run ncmpcpp with the --quiet option it gives me a segmentation fault. I've tested both when another instance of ncmpcpp is running and when not already running with the same result. The version is 0.8-2. Everything else seems to be working fine i.e launching it without -q works as expected with no issues. Would be happy to provide any additional info you may need

**Comment by hghwng** [comment]
Have you tried to build from source? Seems it's a duplicate of #245.

**Comment by julius383** [comment]
No I haven't but if it's the same issue that'll probably solve it, thanks.

**Comment by arybczak** [comment]
FYI, it's fixed in 0.8.1.
