### ISSUE TITLE
[Suggestion] Allow cycling through search results

### ISSUE THREAD

**Issue by realcomplex** [arybczak/ncmpcpp#262]
Hi!

I was wondering if it possible to implement cycling through search results with `n` after using "find forward" by pressing `/`? Something similar to what's implemented in `ncmpc` here: https://github.com/MusicPlayerDaemon/ncmpc/blob/master/src/screen_find.c.

The use case is the following: I might have a library with the following artists:
```
A
A & Z
C
D & Z
...
Z
```
To jump to artist "Z", I have to:

1. Find next occurrence of "Z" - land at "A & Z".
2. Go down one artist.
3. Find next occurrence of "Z" - land at "D & Z".
4. Go down one artist.
5. Find next occurrence of "Z" - finally end up at "Z".

This is a major hassle, and could be much simplified if it were possible to cycle through results by just pressing `n`.

Thanks!

**Comment by arybczak** [comment]
Cycling through search results is bound to ./, (Dot/comma).

12.11.2017 22:55 "realcomplex" <notifications@github.com> napisał(a):

**Comment by realcomplex** [comment]
Well that was easy, sorry for the inconvenience.
