### ISSUE TITLE
please attach proper release tarballs containing configure script to the latest release tag

### ISSUE THREAD

**Issue by rofl0r** [arybczak/ncmpcpp#263]
i understand that you dont want "configure" in your repo, but it is much more convenient for the user when it is shipped as part of the release tarball, which does not happen with the automatic tarball-from-tag feature of github, so it would be great if you could make tarballs containing the autoconf-generated files and attach it to the release tag.

see https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck for more information and how it can be done.

thanks!

(refering from https://github.com/sabotage-linux/sabotage/pull/547 )

**Comment by arybczak** [comment]
All of them can be found at http://rybczak.net/ncmpcpp/stable.

**Comment by rofl0r** [comment]
cool, thanks!
