### ISSUE TITLE
Error while writing tags to <item>: No such file or directory

### ISSUE THREAD

**Issue by hhiru** [arybczak/ncmpcpp#271]
As you can see the file exists but I can't edit its tags. Is this a permission issue? I don't know how to solve it

![image](https://user-images.githubusercontent.com/11262717/34909814-b7e7756a-f8a8-11e7-9dea-dc9ed5a0a0b9.png)

**Comment by hhiru** [comment]
I had $HOME/Music in my ncmpcpp config file and ~/Music in my mpd config file. This was causing the error!

**Comment by Kaanta7** [comment]
More than 4 years later, Thank you.
this was the answer that i was searching for days.
