### ISSUE TITLE
Default quit keybinding has additional key

### ISSUE THREAD

**Issue by dglava** [arybczak/ncmpcpp#272]
The Help screen which shows the keybindings lists another key for the "quit" action. It appears to be an "ė" (Unicode U+0117). See screenshot below. 

I checked the default bindings file and can't find it in it (looked for definitions for the quit action). Is this intended or a bug?

![screen](https://s14.postimg.org/m8hcbrq9d/2018-01-15-13_30_20.png)

Version: 0.8.1

**Comment by arybczak** [comment]
It's a proper keycode, just misformated. Fixed via 0b04d9ec35a8327f5ee734dc70e8b6b8ffa50152.
