### ISSUE TITLE
Metadata showed twice

### ISSUE THREAD

**Issue by leewdch** [arybczak/ncmpcpp#274]
mpd config: https://paste.debian.net/hidden/82a1abc4/
ncmpcpp config: http://paste.debian.net/hidden/2a4031ed/

ncmpcpp 0.8.1
mpd 0.20.15

Everything is showed twice: track name, album, author, composer.. I don't think it's a config issue because other tracks from other albums are totally fine. I tried editing using ncmpcpp tag editor itself but the problem remains

![image](https://user-images.githubusercontent.com/11262717/35186798-4dd6cd0c-fe1a-11e7-9300-ca78a9904b0c.png)
![image](https://user-images.githubusercontent.com/11262717/35186914-5e597844-fe1c-11e7-8d97-03d212b308c4.png)

**Comment by arybczak** [comment]
Set `show_duplicate_tags = no` in configuration file.

Relevant discussion: https://github.com/MusicPlayerDaemon/MPD/pull/2
