### ISSUE TITLE
Changing the clock date format

### ISSUE THREAD

**Issue by tttom64** [arybczak/ncmpcpp#275]
There seems to be no option to change the date format from MM/DD/YY for the clock. Is implementing one viable?

**Comment by arybczak** [comment]
Date format depends on the current locale setting. Why do you want to change it?

**Comment by tttom64** [comment]
That fixed the issue, I'm Australian and I had the locale set to en_US without thinking twice about it. No need to overcomplicate things by adding another option, so closing.

**Comment by cubetastic33** [comment]
I would like to be able to change the clock date format without changing the locale.
