### ISSUE TITLE
Question, adding random songs on command line?

### ISSUE THREAD

**Issue by gerroon** [arybczak/ncmpcpp#276]
Hi

I am sorry if this is not a place to ask for this. 

I really like adding random songs feature but Ncmpcpp needs to be open to do at least it seems that way. Is there a way to add random songs using ncmpcpp without entering the app? Basically I wanto script this so that I can add random songs regularly wihtout too much intervention.

thanks

**Comment by arybczak** [comment]
Yeah, if you want to do something like that, use mpc.
