### ISSUE TITLE
mouse scrolling issue in tmux

### ISSUE THREAD

**Issue by dylnmc** [arybczak/ncmpcpp#277]
Scrolling up with mouse does not work properly when in help in ncmpcpp inside tmux. When you scroll down, it works; when you scroll up, only the first two lines seems to update.

I am not sure why it doesn't work with mouse, but pressing <kbd>up</kbd> works fine and udpates screen fine. However, scrolling up just doesn't work (in help, at least). I have not tried this in other windows/tabs/whatever-they-are-called.

replication:

1. start tmux with `tmux new -s ncmpcpp` (this doesn't matter if another tmux running on same socket, just create new session)

2. start ncmpcpp with `ncmpcpp`

3. press <kbd>F1</kbd> for help

4. make sure mouse support is enabled (you can toggle with <kbd>|</kbd>)

5. scroll down, then scroll up
    - you should see that it doesn't update properly

**Comment by arybczak** [comment]
Works for me. What terminal emulator are you using?

**Comment by dylnmc** [comment]
urxvt

---

It also seems to work for me after updating compton to a newer version.

Thanks
