### ISSUE TITLE
Filtering of search results is broken.

### ISSUE THREAD

**Issue by amaleg** [arybczak/ncmpcpp#279]
On ncmpcpp 8.1, there seems to be some problem with filtering search results.

When applying the filter, I type some characters. As soon as I type a non-matching one, it enters a bugged state. As characters are deleted, the search results do not reappear, even when 'Filtering Disabled'. at that point, search is broken - the up-arrow key does not work but it is still possible to switch to the other screens and use them. If I then try to 'reset' the search, the search screen disappears entirely and this error appears: 
Unexpected error: vector::_M_range_check: __n (which is 11) >= this->size() (which is 0)
At this point I must quit in order to use search again.

This is not a problem on the former version and also the filtering does work fine on all the other screens.

**Comment by arybczak** [comment]
Give me steps to reproduce please.

**Comment by arybczak** [comment]
Nevermind, fixed via 2f3588edf39a93143816f250d5c5a3af57af6b35
