### ISSUE TITLE
media_library_primary_tag = "album_artist" # and if empty "artist"

### ISSUE THREAD

**Issue by liviurad** [arybczak/ncmpcpp#280]
Shortly said, it would be nice to support this in the config: `media_library_primary_tag = "{%A}|{%a}"`

Support for fallback tag to **artist** when **album_artist** is empty. Or full support to specify a tag to be displayed in each column like in the example above.

**Comment by arybczak** [comment]
https://github.com/arybczak/ncmpcpp/blob/master/extras/artist_to_albumartist.cpp will fix your library, i.e. copy artist to albumartist whenever it's not present.

**Comment by liviurad** [comment]
Thank you very much. That looks to me more like a workaround. But is this really a problem of the library? I would say not. To it makes a lot more sense to be a feature of the player. 

If I try to do it, would you accept the patch in the player?
