### ISSUE TITLE
Undefined keyboard shortcut added

### ISSUE THREAD

**Issue by dglava** [arybczak/ncmpcpp#287]
I have bound "ctrl-m" to "move_selected_items_to". It works, but it also somehow bound "enter" to it as seen in the screenshot and I can also move selected items with it as well.

Where is the "enter" coming from?

Screenshot of the Help screen:
https://s31.postimg.cc/sscxe682j/2018-04-14-11_13_12.png

Here is my config file:
https://gist.github.com/dglava/7763341c2fcd30dd123a771456c709e8

**Comment by arybczak** [comment]
The problem is that it's impossible to distinguish between ctrl-m and enter in terminal as both produce the same keycode (13). All terminal apps have this issue (there is a similar problem with Tab and ctrl-i)

**Comment by dglava** [comment]
Thank you for the explanation. I will just bind it to something else.
