### ISSUE TITLE
Header displays warning from `find` on some tracks whose tags contain forward slashes

### ISSUE THREAD

**Issue by fictionic** [arybczak/ncmpcpp#293]
I have a track whose artist and album_artist are `Dr. Pez/Marc Papeghin`, and when playing this track ncmpcpp prints a warning from `find` about files having slashes in their names. This shouldn't happen.

**Comment by arybczak** [comment]
It's a warning from MPD.

**Comment by fictionic** [comment]
Ah, thanks!
