### ISSUE TITLE
Feature: Shuffle only selected songs in playlist

### ISSUE THREAD

**Issue by quite** [arybczak/ncmpcpp#30]
An action/key to shuffle only selected songs in the playlist.

I rather often find myself adding a few albums to my playlist, but then wanting to play them all shuffled. And I don't wanna destroy the rest of my playlist just for that.

**Comment by Ploppz** [comment]
Maybe this could be the default behaviour when pressing `Z` when having songs selected?

**Comment by arybczak** [comment]
Good idea, done in master.

**Comment by quite** [comment]
Wohoo!
