### ISSUE TITLE
provide configuration documentation

### ISSUE THREAD

**Issue by ghistes** [arybczak/ncmpcpp#311]
Hi,

at least for me (please excuse my stupidity) the provided example-configuration is not enough to figure out how to configure the appearance of ncmpcpp.

E.g. I simply cannot find the variables to use to change certain colors.

I just thought "active_column_color" is what I was looking for, except that it isn't (and I don't know what it really does).

Everytime I have to resort to an hour of googling, tweaking and experimenting of what should be a simple reference to a proper documentation.

Sorry for the rant, but for the time being I am giving up on it.

**Comment by arybczak** [comment]
Hey,

`man ncmpcpp` has description for all configuration variables.

**Comment by ghistes** [comment]
Yeah? Does it? 
Look, my problem is that I have black-on-white terminals. Then the default colors are horrible.
In my media library the selected items are white on yellow. How do I change that to something sensible?
I don't know and the manpage with all it's "descriptions" (not a term I would use for that blah-blah) won't tell me.
I am tired of trial and error.
The software is great but the docs are shite. 
Sorry for being blunt.

**Comment by arybczak** [comment]
> How do I change that to something sensible?

You alter the colors.

**Comment by arybczak** [comment]
I'll give you a hint: if you open man page and type `/color <enter>`, you'll have all the info you need. It looks like man page is outdated if it comes to background colors, but that info can be found in the example config file.

**Comment by arybczak** [comment]
Look at current_item_prefix/suffix and current_item_inactive_column_prefix/suffix.

**Comment by tansly** [comment]
Do you have a suggestion for documenting current_item_prefix in a better way? How are you trying to explain the transcendental concept of "the prefix for the currently selected item" in a human language for our human brains to understand? It is literally the prefix for the currently selected item in all its glory.

**Comment by arybczak** [comment]
Alright, I am not going to continue this conversation, good bye.
