### ISSUE TITLE
Opening lyrics always shows lyrics for the song played when ncmpcpp was started

### ISSUE THREAD

**Issue by ilyazzz** [arybczak/ncmpcpp#334]
Running ncmpcpp 0.8.2 on Arch Linux, with MPD as a user service.

Pressing L to open lyrics will always show lyrics for the song, that was playing at the time when ncmpcpp was started. You have to re-open ncmpcpp to show the lyrics for next song.

**Comment by arybczak** [comment]
Lyrics screen shows lyrics for the song that is currently selected, not the one that's currently playing.
