### ISSUE TITLE
[BUG][minor] Crashes if `lyrics_directory` is under a not yet created directory

### ISSUE THREAD

**Issue by buzuck** [arybczak/ncmpcpp#336]
ncmpcpp doesn't start if `lyrics_directory` is inside an nonexistent directory.

----

If you have `lyrics_directory = ~/.cache/ncmpcpp/lyrics`, but no `ncmpcpp` in `.cache`, it crashes.
However, it doesn't if `~/.cache/ncmpcpp` exists, and the path `~/.cache/ncmpcpp/lyrics` is created.

**Comment by sticken88** [comment]
Hi,
I created a pull request with a change that might fix the issue.
Reference here: https://www.boost.org/doc/libs/1_69_0/libs/filesystem/doc/reference.html#create_directories

Hope it helps. Feel free to post your comment.
