### ISSUE TITLE
configure does not check for readline

### ISSUE THREAD

**Issue by cweiske** [arybczak/ncmpcpp#34]
`configure` ran fine on Ubuntu 14.04, but then `make` stopped because `readline/readline.h` could not be found. Configure should check for that probably.

**Comment by arybczak** [comment]
That's weird, because configure actually checks for readline/readline.h. Can you paste the output of configure? The check should be between checks for libmpdclient and pthread.

**Comment by arybczak** [comment]
No response, closing.

**Comment by cweiske** [comment]
```
...
checking for libmpdclient... yes
checking mpd/client.h usability... yes
checking mpd/client.h presence... yes
checking for mpd/client.h... yes
checking readline/readline.h usability... no
checking readline/readline.h presence... no
checking for readline/readline.h... no
checking readline/history.h usability... no
checking readline/history.h presence... no
checking for readline/history.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
...
```

**Comment by arybczak** [comment]
Ahh, I see, the configure script doesn't do its job fully. Thanks for the update, I corrected the issue.
