### ISSUE TITLE
ncmpcpp crashes with mopidy-soundcloud extension

### ISSUE THREAD

**Issue by jakehemmerle** [arybczak/ncmpcpp#35]
When selecting the [Likes] box while connected to mopidy, ncmpcpp times out, freezes, and after after crashing, it spews 15ish characters into the terminal box. Sounds like it could be a security issue as well, if the output could be controlled and have a return statement. Anyway, it appears to be a ncmpcpp issue, not mopidy-soundcloud. I did see this bug submitted on the mopidy-soundcloud repo as well.

Thanks for all the work on this great client!

**Comment by arybczak** [comment]
What is "[Likes] box"?

**Comment by jakehemmerle** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8061957/7284707/7eb20ff6-e90d-11e4-8a57-cb6d3c354acc.png)

My apologies, bottom right. Unfortunately, I do not get any crash log. I am not familiar with debugging C++.

**Comment by arybczak** [comment]
I see.
http://ncmpcpp.rybczak.net/faq.php - check out the last question. I need a backtrace to identify the problem.

**Comment by jakehemmerle** [comment]
Having lots of issues with the boost library... I'm on Arch Linux... Is there any place I can download the precompiled binary with the debugging flags? Ill keep fiddling in the mean time.

**Comment by jakehemmerle** [comment]
Unfortunately, it will not compile. I hate to ask, but can you provide a precompiled binary with debugging flags set? I cannot seem to get it to compile.

<addr>
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT search_engine.o -MD -MP -MF .deps/search_engine.Tpo -c -o search_engine.o search_engine.cpp
In file included from search_engine.cpp:23:0:
/usr/include/boost/range/detail/any_iterator.hpp:131:15: error: 'postfix_increment_proxy' is not a class template
         class postfix_increment_proxy<
               ^
/usr/include/boost/range/detail/any_iterator.hpp:176:15: error: 'writable_postfix_increment_proxy' is not a class template
         class writable_postfix_increment_proxy<
               ^
mv -f .deps/screen_type.Tpo .deps/screen_type.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT sel_items_adder.o -MD -MP -MF .deps/sel_items_adder.Tpo -c -o sel_items_adder.o sel_items_adder.cpp
mv -f .deps/playlist_editor.Tpo .deps/playlist_editor.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT server_info.o -MD -MP -MF .deps/server_info.Tpo -c -o server_info.o server_info.cpp
mv -f .deps/scrollpad.Tpo .deps/scrollpad.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT settings.o -MD -MP -MF .deps/settings.Tpo -c -o settings.o settings.cpp
mv -f .deps/media_library.Tpo .deps/media_library.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/usr/include/taglib  -g -O2 -std=c++0x -MT song.o -MD -MP -MF .deps/song.Tpo -c -o song.o song.cpp
Makefile:587: recipe for target 'search_engine.o' failed
make[2]: *** [search_engine.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/song.Tpo .deps/song.Po
mv -f .deps/sel_items_adder.Tpo .deps/sel_items_adder.Po
mv -f .deps/server_info.Tpo .deps/server_info.Po
mv -f .deps/settings.Tpo .deps/settings.Po
make[2]: Leaving directory '/tmp/ncmpcpp/src'
Makefile:463: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/ncmpcpp'
Makefile:374: recipe for target 'all' failed
make: *** [all] Error 2
</addr>

**Comment by arybczak** [comment]
The problem is that the latest boost version is broken (and I assume Arch gives you only the newest version). You can use the workaround from here: http://bugs.musicpd.org/view.php?id=4352

**Comment by jakehemmerle** [comment]
Gah, its been 3 hours. I'll try it again once they fix this issue.

**Comment by arybczak** [comment]
boost version was updated, so it should compile now.

**Comment by arybczak** [comment]
No feedback, closing. Reopen when you are able to provide a backtrace, please.

**Comment by jakehemmerle** [comment]
Will do! I apologize, I haven't had much free time lately with school and trying to start a small business. I'll let you know as soon as I can complete what's needed above.
