### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by arybczak** [arybczak/ncmpcpp#350]
Hey everyone,

As you've probably noticed ncmpcpp has been on (less than) life support for a long time now.

The primary reason is that I've moved on - I don't listen to music so much anymore. I'm still using ncmpcpp, but only its basic features. I've also started leaning towards Spotify more and more because of convenience.

If anyone is interested in picking up maintenance, please let me know.

**Comment by roosemberth** [comment]
Fwiw, I use ncmpcpp to browse and listen stuff on spotify through mopidy ^^

**Comment by SicariusNoctis** [comment]
[mopidy-spotify](https://github.com/mopidy/mopidy-spotify). Also, it might be a good idea to pin this issue.

**Comment by larson-carter** [comment]
@arybczak I'm down with maintaining this project!

**Comment by larson-carter** [comment]
> Hey everyone,
> 
> As you've probably noticed ncmpcpp has been on (less than) life support for a long time now.
> 
> The primary reason is that I've moved on - I don't listen to music so much anymore. I'm still using ncmpcpp, but only its basic features. I've also started leaning towards Spotify more and more because of convenience.
> 
> If anyone is interested in picking up maintenance, please let me know.

Feel free to ping me on discord larson_carter#4511

**Comment by adhirajsinghchauhan** [comment]
@arybczak me too. @larson-carter and I are in the same team, so it'll be great if we can maintain this project together (along with the rest of our team)

you can find me one Discord: ascii#1846

**Comment by larson-carter** [comment]
@arybczak If you can add him that'll be great.

**Comment by adhirajsinghchauhan** [comment]
@arybczak @larson-carter and I have sent you an email, could we setup a quick meeting to discuss this project and future plans?

**Comment by arybczak** [comment]
Sure. What timezone are you in?

**Comment by adhirajsinghchauhan** [comment]
@arybczak Let's communicate over email: adhirajsinghchauhan@gmail.com
