### ISSUE TITLE
[FEATURE] Add UPNP browser 

### ISSUE THREAD

**Issue by montaintop** [arybczak/ncmpcpp#361]
NCMPCPP is great for browsing MPD library. 

However it would be even better to have UPNP/DLNA server browser built in:)

**Comment by larson-carter** [comment]
@montaintop Hello, thank you for creating this issue.

Are your referring to something similar to this:  https://www.lesbonscomptes.com/pages/mpd-upnp.html

**Comment by montaintop** [comment]
Yep, just the current MPD upnp plug in is kind of buggy. It would be great to be able to do it in NCMCPPP to access MPD internal database and upnp one together. Not sure where this feature should be more relavant though. thank you.

**Comment by montaintop** [comment]
Found solution using MPD plug in
