### ISSUE TITLE
next_screen/previous_screen only switches between first two screens

### ISSUE THREAD

**Issue by OliverLew** [arybczak/ncmpcpp#363]
**Describe the bug**

Edit: Sorry didn't see the option to open a blank issue, this is probably not a bug :)

I am not sure it's a bug or it's just me confusing about the behavior:
Executing the "next_screen" or "previous_screen" keybinding (one of the two) multiple times only switches between playlist and browser screen.

Is this the expected behavior? If so, how can I easily switch from the first screen (playlist) all the way to the last (visualizer)?

P.S. While looking into binding config file, I thought of this, although a little bit hacky and need a lot of keybindings:
```
def_key "shift-tab"
  require_screen "playlist"
  push_characters "8"

def_key "shift-tab"
  require_screen "visualizer"
  push_characters "7"

... (do this for all the rest, and the same but backward for "tab" keybindings)
```

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Terminal: bash
 - Version ncmpcpp 0.8.2

**Additional context**

**Comment by arybczak** [comment]
There is `screen_switcher_mode` in the configuration file for defining the sequence of screens you want to switch through.

**Comment by OliverLew** [comment]
Oh, thank you! I haven't thought there is an option to configure this. I guess I didn't go through the config file carefully enough the first time :) I will close the issue then.
