### ISSUE TITLE
[BUG] lyrics fetcher can't fetch any lyrics

### ISSUE THREAD

**Issue by Thorondir** [arybczak/ncmpcpp#372]
**Describe the bug**
Trying to fetch the lyrics of a song is met with "Not Found" for every source, for every track, without fail. The recommended source from "the Internet" gives a working link to the lyrics from one of the sources ncmpcpp was meant to scrape from (provided the lyrics actually exist for the song).
The issue was in `GoogleLyricsFetcher::fetch`, where ncmpcpp would retrieve the url to a google redirect page and expected the redirect page to be the page hosting the lyrics.

**To Reproduce**
1. Select a song
2. Press `l` to fetch lyrics
3. Witness.

**Expected behavior**
Expected for ncmpcpp to scrape through a few sources before finding and displaying the lyrics.

**Screenshots/Logs (none provided)**
(no screenshot because I fixed this on my end)

**Desktop (please complete the following information):**
 - OS: Arch (5.4.7-arch1-1)
 - Terminal: zsh on Termite
 - Version: 0.9_dev

**Fix**
Bypassed the redirect page by changing the regex on line 243 from `"<A HREF=\"(.*?)\">here</A>"` to `"<A HREF=\"http://www.google.com/url\\?q=(.*?)\">here</A>"`.

**Comment by arybczak** [comment]
Thanks for investigating this :)
