### ISSUE TITLE
libboost dependencies

### ISSUE THREAD

**Issue by johnso51** [arybczak/ncmpcpp#40]
The libboost dependencies seem to require libboost_*.so.57.0
libboost is currently at 58.0, so maybe these should point to the generic libboost_*.so, rather than a specific version.

**Comment by arybczak** [comment]
Configure script doesn't check for any specific version. Why do you think it does?

**Comment by johnso51** [comment]
This was a runtime issue. It looks like it is due to the fact that my distros package manager has version 0.6.3, so the deps were messed up. Library was updated, but not ncmpcpp. My mistake, I will close.
