### ISSUE TITLE
readline error when compiling

### ISSUE THREAD

**Issue by jostber** [arybczak/ncmpcpp#43]
When I compile it errors out with:

checking for readline/readline.h... yes
checking for rl_initialize in -lreadline... no
configure: error: readline headers found but there is no readline library to make use of

I use Slackware 14.1 64 bit. Anything to check here?

**Comment by arybczak** [comment]
No idea. Do you have the library in a non-standard location or something?

**Comment by jostber** [comment]
This Slackware installation is a vanilla one. Libs are here:

jostein:~/dw/ncmpcpp$ ls /usr/lib64/libread*
/usr/lib64/libreadline.a  /usr/lib64/libreadline.so  /usr/lib64/libreadline.so.5  /usr/lib64/libreadline.so.5.2

**Comment by arybczak** [comment]
Does config.log contain any useful information?

**Comment by jostber** [comment]
On 13.06.15,09:20, Andrzej Rybczak wrote:
> Does config.log contain any useful information?
> 

Some excerpts from the config.log here:


configure:16023: result: yes
configure:16023: checking readline/readline.h presence
configure:16023: g++ -E      conftest.cpp
configure:16023: $? = 0
configure:16023: result: yes
configure:16023: checking for readline/readline.h
configure:16023: result: yes
configure:16028: checking for rl_initialize in -lreadline
configure:16053: g++ -o conftest -g -O2 -std=c++0x       conftest.cpp
-lreadline   -lboost_filesystem -lboost_system -lboost_locale
-lboost_program_options -lboost_regex -licuuc -licudata   -lboost_thread
-lmpdclient   >&5
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tgetnum'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tgetent'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tgetstr'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tgoto'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `UP'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `BC'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tputs'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `PC'
/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/../../../../lib64/libreadline.so:
undefined reference to `tgetflag'
collect2: error: ld returned 1 exit status
configure:16053: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "" |


.....

 #define HAVE_BOOST_THREAD_HPP 1VE_LANGINFO_H 1
| #define HAVE_MPD_CLIENT_H 1
| #define HAVE_READLINE_READLINE_H 1
| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char rl_initialize ();
| int
| main ()
| {
| return rl_initialize ();
|   ;
|   return 0;
| }
configure:16062: result: no
configure:16067: error: readline headers found but there is no readline
library to make use of                                                                                                                                                                                                                                                                     
| #define HAVE_NETINET_TCP_H 1
|  HAVE_NETINET

**Comment by shpritsz** [comment]
@jostber Have you found a fix for this?

I am running into the same issue, on Slackware-current using ncmpcpp-0.6.7 as well as latest git (2015-11-11).

**Comment by jostber** [comment]
On 11.11.15,04:47, shpritsz wrote:
> @jostber Have you found a fix for this?
> 
> I am running into the same issue, on Slackware-current using ncmpcpp-0.6.7 as well as latest git (2015-11-11).
> 

I tried with the newest git now as well and gets the same error.

**Comment by arybczak** [comment]
It should be fixed in git now.

**Comment by shpritsz** [comment]
Sweet!  All is well.
Thanks a lot for the quick repsonse!

**Comment by jostber** [comment]
On 11.11.15,06:37, Andrzej Rybczak wrote:
> It should be fixed in git now.
> 

The readline error is gone now, but it now gives this error when running
make:

tags.cpp: In function ‘bool Tags::write(MPD::MutableSong&)’:
tags.cpp:298:65: error: no matching function for call to
‘TagLib::MPEG::File::save(TagLib::MPEG::File::TagTypes, bool, int, bool)’
if (!mpeg_file->save(TagLib::MPEG::File::ID3v2, true, 4, false))
^
tags.cpp:298:65: note: candidates are:
In file included from tags.cpp:30:0:
/usr/include/taglib/mpegfile.h:173:20: note: virtual bool
TagLib::MPEG::File::save()
virtual bool save();
^
/usr/include/taglib/mpegfile.h:173:20: note:   candidate expects 0
arguments, 4 provided
/usr/include/taglib/mpegfile.h:184:12: note: bool
TagLib::MPEG::File::save(int)
bool save(int tags);
^
/usr/include/taglib/mpegfile.h:184:12: note:   candidate expects 1 argument,
4 provided
/usr/include/taglib/mpegfile.h:196:12: note: bool
TagLib::MPEG::File::save(int, bool)
bool save(int tags, bool stripOthers);
^
/usr/include/taglib/mpegfile.h:196:12: note:   candidate expects 2
arguments, 4 provided
/usr/include/taglib/mpegfile.h:211:12: note: bool
TagLib::MPEG::File::save(int, bool, int)
bool save(int tags, bool stripOthers, int id3v2Version);
^
/usr/include/taglib/mpegfile.h:211:12: note:   candidate expects 3
arguments, 4 provided
make[2]: *** [tags.o] Error 1
make[2]: Leaving directory `/home/jostein/dw/ncmpcpp/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/jostein/dw/ncmpcpp'

**Comment by arybczak** [comment]
This is irrelevant to this issue, please open separate one and provide the version of taglib you have.

**Comment by jostber** [comment]
On 12.11.15,03:39, Andrzej Rybczak wrote:
> This is irrelevant to this issue, please open separate one and provide the version of taglib you have.
> 

Thanks, I have now opened a new issue.

Jostein
