### ISSUE TITLE
closed azlyrics API, can't get the lyrics

### ISSUE THREAD

**Issue by toogy** [arybczak/ncmpcpp#45]
When trying to retrieve a song's lyrics with ncmpcpp, it tries to retrieve them from **azlyrics** when *lyricswiki* doesn't have them.

But I think that **azlyrics** closed their API. azlyrics.com respons with:
> Visit www.azlyrics.com for these lyrics.

ncmpcpp then considers that azlyrics responded correctly and gives me this error message as the lyrics.

Is it possible to remove azlyrics from the lyrics fetcher's sources?

**Comment by arybczak** [comment]
Fixed in 0.6.5.

**Comment by seirl** [comment]
Still getting this error in 0.7_pre

**Comment by seirl** [comment]
nvm, rebasing on 7563274 fixed it
