### ISSUE TITLE
F1 for help doesn't work

### ISSUE THREAD

**Issue by tvamsisai** [arybczak/ncmpcpp#46]
*I'm new to using ncmpcpp. On top of which I just, a few hours ago, realised I hadn't installed the newest version. Did a lot of things to get the source compiled, after removing the installation from apt-get.*

Now to get to the 'help' tab I was supposed to press F1, but sadly it doesn't work on my Ubuntu. **It opens up the GNOME Terminal's help.**

I fixed it for myself by rebinding the 'help' tab to non-binded '0' key. I think this should be done by default.

**Comment by arybczak** [comment]
This is terminal specific problem, apparently GNOME Terminal captures F1 itself.
