### ISSUE TITLE
Lyrics as slave screen

### ISSUE THREAD

**Issue by hetraeus** [arybczak/ncmpcpp#48]
Hello I wonder if it will be possible to have lyrics as slave screen. Is it planned?

**Comment by arybczak** [comment]
No (what would be displayed there?), but you can set startup_slave_screen to 'playlist', so that ncmpcpp starts will playlist locked and you can fire lyrics immediately.

**Comment by arybczak** [comment]
You mean as the one on the right?

**Comment by hetraeus** [comment]
The idea is to have a panel, no matter which one, with the playlist (or anything) and the other with the lyrics of the current song. Without need to fire them, already there from the startup. Of course it is not vital, just a nice have.

**Comment by arybczak** [comment]
The bit of locking a screen is already there (startup_slave_screen config variable). All that is needed is some customizable action to be run at startup, which makes sense to be implemented.

**Comment by arybczak** [comment]
4cd94cb4b3419517bfef1471a08ceb1cb438077a
