### ISSUE TITLE
Library does not sort track number properly.

### ISSUE THREAD

**Issue by easysid** [arybczak/ncmpcpp#50]
It looks like that the library sorts track 100 before track 11, leading to the following situation

![image of library](http://i.imgur.com/f9FAEVH.png).

Moreover, it does not matter whether track number is displayed or not (using *song_library_format*), the sort remains the same (S is sorted in between the A's).

**Comment by arybczak** [comment]
Yeah, track numbers are in general sorted as strings, not as numbers. I can override this behavior for media library specifically though.

**Comment by arybczak** [comment]
Also, what version are you using? song_library_format was removed ages ago.

**Comment by easysid** [comment]
Thanks for the reply.
Yes, the version is a bit outdated. I am using the git build and haven't synced in a while. Will do so immidiately.

**Comment by arybczak** [comment]
Ah, sorry, I confused the format of the right column with the format of the middle column, nevermind my last comment.

**Comment by arybczak** [comment]
Fixed by 8f9a1a8fc0a8cdf108216a3e51a76f42d691cf18

**Comment by easysid** [comment]
Thanks for the fix.
