### ISSUE TITLE
[Suggestion] genius.com lyrics fetcher

### ISSUE THREAD

**Issue by untitaker** [arybczak/ncmpcpp#52]
Genius/RapGenius has the by far best lyrics database I've ever encountered. Note that I don't feel particularly strong about this, I don't have use for it myself. It's just something that came to my mind when reading through #45.

It seems their developer API requires registration, but http://genius-api.com/ seems to be very usable.

**Comment by zzggbb** [comment]
Also, azlyrics.com should probably be removed as a lyrics source, instead of fetching lyrics it just returns "Visit www.azlyrics.com for these lyrics"

**Comment by arybczak** [comment]
@zzggbb This was fixed in 0.6.5 and is now on master, I forgot to push the patch there earlier.

@untitaker Care to write a patch that adds support for this?

**Comment by arybczak** [comment]
Already on master, closing.
