### ISSUE TITLE
ncmpcpp: Response line too large

### ISSUE THREAD

**Issue by ghosthoughts** [arybczak/ncmpcpp#55]
ncmpcpp fails to connect to mpd with the error mentioned in the title.

Here is the related log of mpd server:

    % mpd --verbose --stdout --no-daemon
    config_file: loading file /home/ghost/.config/mpd/mpd.conf
    path: SetFSCharset: fs charset is: UTF-8
    libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
    vorbis: Xiph.Org libVorbis 1.3.5
    opus: libopus 1.1
    sndfile: libsndfile-1.0.25
    db: reading DB
    curl: version 7.43.0
    curl: with OpenSSL/1.0.2d
    avahi: Initializing interface
    avahi: Client changed to state 2
    avahi: Client is RUNNING
    avahi: Registering service _mpd._tcp/Music Player
    avahi: Service group changed to state 0
    avahi: Service group is UNCOMMITED
    state_file: Loading state file /home/ghost/.config/mpd/state
    avahi: Service group changed to state 1
    avahi: Service group is REGISTERING
    avahi: Service group changed to state 2
    avahi: Service 'Music Player' successfully established.
    client: [0] opened from local
    client: [0] process command "status"
    client: [0] command returned 0
    client: [0] process command "lsinfo "/""
    client: [0] command returned 0
    client: [0] closed
    client: [1] opened from local
    client: [1] process command "status"
    client: [1] command returned 0
    client: [1] process command "lsinfo "/""
    client: [1] command returned 0
    client: [1] closed
    client: [2] opened from local

Thinking that this has something to do with the output buffer I also set the `max_output_buffer_size` to varying values ranging from `"9999"` to the possible unrealistic `"99999"`, but ncmpcpp just wouldn't connect.
In contrast, ncmpc and cantata connected successfully to the same server.

**Comment by arybczak** [comment]
Can you connect to mpd via telnet/netcat (`telnet localhost 6600` or `netcat localhost 6600`) and see what output does `lsinfo "/"` produce?

**Comment by ghosthoughts** [comment]
Sorry for replying so late! Life has been quite busy.
I managed to find the issue - there was one mp3 file which _ncmpcpp_ wasn't able to deal with for some reason unknown to me. _cantata_ and _ncmpc_ were able to run the file, but _ncmpcpp_ and _vimpc_ failed to initialize the UI in the first place. Unfortunately, I deleted the file then, realizing too late that it could have helped in debugging. After that, _ncmpcpp_ is working quite happily. I love this piece of software! Thanks for making it. :-)

**Comment by arybczak** [comment]
Thanks for the update.

**Comment by napcae** [comment]
I'll get the same error(Response line too large) if I'm opening the playlist view(5). [Here](https://gist.github.com/napcae/9fe18d71cc1b15d7e578) is my output. If you need more information, I'm glad to help.

**Comment by ravench** [comment]
Had the same issue, the reason was a id3-field containing to a to-long string.

**Comment by zSucrilhos** [comment]
I'm still having the same issue. I already tryied launching it with a empty playlist and used Mp3Tag to look a each individual id3 tags of the files, there was no annormaly (special characters, too long strings or anything else that could catch one's attention, they just seemed normal).

**Comment by adhirajsinghchauhan** [comment]
> Ncmpcpp can't handle playlists with 11.000 entries.
@napcae What made you reach the conclusion of a hard limit of 11k? Did you try it with 10999, for example?

> the reason was a id3-field containing to a to-long string.
@ravench Could you post that string here?

I'll try reproducing it on my end, and come back with an update

**Comment by napcae** [comment]
Can't recall anymore, I guess that was a playlist with all my songs.

**Comment by ravench** [comment]
> > @ravench Could you post that string here?

Sorry, that String didn't survive the last four years...

**Comment by m040601** [comment]
> .... there was one mp3 file which ncmpcpp wasn't able to deal with for some reason unknown to me....failed to initialize the UI in the first place. ....

> 
... look a each individual id3 tags of the files, there was no annormaly (special characters, too long strings or anything else that could catch one's attention....


I had this issue to, and have written about it in,
https://github.com/ncmpcpp/ncmpcpp/issues/380
