### ISSUE TITLE
Search produces UTF-8 / UTF-32 error

### ISSUE THREAD

**Issue by djvs** [arybczak/ncmpcpp#57]
`Unexpected error: Invalid UTF-8 sequence encountered while trying to encode UTF-32 character` appears where you normally see song playing.   The same string entered into the search (in Playlist view) will generate the error immediately after a character is typed, but not necessarily the same character..

Possibly related, erratic scrolling seems to happen after this is triggered (it might have just been that a database update was initiated).

**Comment by djvs** [comment]
I bet it has something to do with the search feature auto-scrolling to the next song.  I have all kinds of messed up song titles.

**Comment by arybczak** [comment]
51768b9f7a582fee2ddd7a45da1fb2946a202cfe should fix that, but ultimately you need to fix your tags.

**Comment by djvs** [comment]
Trying it now.  What is wrong with my tags though?

**Comment by arybczak** [comment]
> I have all kinds of messed up song titles.

?

Some of your tags are apparently invalid utf-8.

**Comment by djvs** [comment]
Seems to work (i.e. not crash) now.  Probably not worth my effort past there, right?

**Comment by arybczak** [comment]
That depends, it now just ignores this error and goes to the next position, so the ones that trigger this error will never be marked as found.

**Comment by arybczak** [comment]
I added a log message that gets written to error.log file in ncmpcpp directory about the invalid strings, that should make them easy to identify and fix.

**Comment by djvs** [comment]
Great, thank you, it's looking very good.
