### ISSUE TITLE
ncmpcpp lyrics panel can't read txt files

### ISSUE THREAD

**Issue by yzoug** [arybczak/ncmpcpp#59]
A txt file with the right name is present in my lyrics folder but the lyrics panel of ncmpcpp is blank (see below). Pressing 'e' to edit the file opens it with no problem (again, below) but still, the built-in panel of ncmpcpp doesn't show it (even after modification). It only shows the ones I downloaded using the soft itself and its downloader.
![scrnshot1](https://cloud.githubusercontent.com/assets/2179588/9469373/f1bca7f4-4b46-11e5-862b-37f0903b9c90.png)
![scrnshot2](https://cloud.githubusercontent.com/assets/2179588/9469374/f1c11f28-4b46-11e5-8d58-d826e6d4cd22.png)
Other song, same problem (it happens really with every single txt file that isn't downloaded directly by ncmpcpp)
![2015-08-25-143512_1366x768_scrot](https://cloud.githubusercontent.com/assets/2179588/9469470/7cc016d8-4b47-11e5-953c-b62c08e661fc.png)
![2015-08-25-143517_1366x768_scrot](https://cloud.githubusercontent.com/assets/2179588/9469476/849eb882-4b47-11e5-8d71-39241de0c04e.png)
With this one I tried opening the lyric with ncmpc, it works perfectly:
![2015-08-25-143533_1366x768_scrot](https://cloud.githubusercontent.com/assets/2179588/9469493/a441fcc6-4b47-11e5-83fa-b1a7f24333e7.png)
Config file: http://arin.ga/aYj2ij
I'm using Arch, last ncmpcpp (0.6.5). Thanks!

**Comment by arybczak** [comment]
Does it happen with all tracks or only specific ones?

**Comment by yzoug** [comment]
With every track if the lyrics aren't downloaded by ncmpcpp

**Comment by arybczak** [comment]
Umm, that's weird. Maybe your editor adds something to the files that breaks it?

**Comment by yzoug** [comment]
Okey, it's been a while but I figured out the problem: the files were DOS txt files and while vim can open them with no problem, ncmpcpp can't. If you have a similar issue, check your txt files with `file`, it should return something like "ASCII text with CRLF line terminators". Install and run dos2unix on the files to resolve the problem, `file` will then return "ASCII text".

**Comment by arybczak** [comment]
Fixed with dac0d4602f810d8f43e18beefdd43068e40308c3.
