### ISSUE TITLE
ncmpcpp doesn't load cue files properly

### ISSUE THREAD

**Issue by petronny** [arybczak/ncmpcpp#60]
now ncmpcpp will do as follows when loading a *.cue:
1. send command:`listplaylist "a.cue"` to the mpd server, then the server will reply:
```
file: a.ape
file: a.ape
...
file: a.ape
```

2. then for each `a.ape` above , do `addid "a.ape"`

and finally the playlist is appended with many `a.ape`, not the tracks discribed in `a.cue`.

__But ncmpc will load it right !__

ncmpc will just submit `load "a.cue"` to the server, and the tracks are loaded.

I tried to fix this but failed. I can not find the word `listplaylist` in the whole repo.

Could you fix this if you have time, or give me some hints about how to fix this?
Thanks

**Comment by arybczak** [comment]
What version? Also, how exactly are you loading the playlist?

**Comment by petronny** [comment]
at commit 1912. I'm compiling the latest version now.

i load the cue file as follows:

* press `2` to list the directory
* navigate to the cue file
* press `enter` or `a`

**Comment by arybczak** [comment]
Does the playlist load properly when you press space?

**Comment by petronny** [comment]
wow, yes

**Comment by arybczak** [comment]
Btw, what mpd version do you have? I thought cue support was removed from mpd at some point.

**Comment by petronny** [comment]
0.19.10

**Comment by petronny** [comment]
but why i cannot find the word listplaylist in the whole repo?

**Comment by arybczak** [comment]
Because it's libmpdclient that wraps raw commands.

**Comment by arybczak** [comment]
Loading with Enter also should work properly. I can't do anything about loading it with 'a' though. The problem is the inconsistent (and most likely incorrect) behavior of MPD.

**Comment by petronny** [comment]
Thank you very much. Will u issue the detail of the inconsistent behavior to MPD?

**Comment by kovaga** [comment]
4 years onwards and the bug is still present :)
ncmpcpp 0.8.1
Music Player Daemon 0.20.18 (128d910-dirty)
