### ISSUE TITLE
add deselect all or select all action

### ISSUE THREAD

**Issue by incertia** [arybczak/ncmpcpp#61]
one would imply the other. for example, deselect all + invert selection ==> select all. the current way i do this (not sure if there is another way) is to make sure the first and last are selected, and then select range.

**Comment by arybczak** [comment]
v/V already does what you want.

**Comment by incertia** [comment]
oops i thought `V` removed selection from the playlist. maybe rename this to deselect all?

**Comment by arybczak** [comment]
It's described as "Remove selection" on help screen. Is that not clear?

**Comment by arybczak** [comment]
Can you clarify?

**Comment by incertia** [comment]
just me being stupid. thought V did the same reason as Delete for some reason

**Comment by arybczak** [comment]
Ah, I see. I didn't think that it may be interpreted like this. Maybe "deselect items" is indeed a better description.
