### ISSUE TITLE
add better range selection

### ISSUE THREAD

**Issue by incertia** [arybczak/ncmpcpp#62]
ideally this would be something like vim's visual line mode and appends to the current selection. you push a key (say V) to toggle the selection mode and use up/down to move selection in a direction. the current workaround would be to use something like this in ~/.ncmpcpp/bindings
```
def_key "J"
  select_item
  scroll_down
def_key "K"
  select_item
  scroll_up
```

**Comment by arybczak** [comment]
Currently that's the intended way to that actually.

**Comment by incertia** [comment]
ah ok. thanks.
