### ISSUE TITLE
customize highlight color

### ISSUE THREAD

**Issue by r8b7xy** [arybczak/ncmpcpp#68]
Right now highlight color is simply reverse mode. It'd be handy to customize both fg and bg color of highlighting.

**Comment by tfinnell** [comment]
This would be great for transparent terms where we see selected items similar to the screenshots in this question:
http://unix.stackexchange.com/questions/115169/how-to-change-a-font-background-color-in-transparent-windows

**Comment by arybczak** [comment]
See 19d32648ed4ad04c4cc09fd7ec6b9250b9387893.
