### ISSUE TITLE
Keyboard command to filter songs no longer works

### ISSUE THREAD

**Issue by ChimeraCoder** [arybczak/ncmpcpp#71]
Last week I updated from an older version of ncmpcpp to the latest version of `ncmpcpp-git`from the AUR (output of `ncmpcpp --version` is `ncmpcpp 0.7_dev`, though I am not sure if trunk releases are version tagged this way).

In the process, a number of keyboard shortcuts changed (`P` became `p`, and vice versa, etc.). I can adjust to these and am not looking to change them; however, it appears that the ability to filter songs has been removed. Previously this was bound to `Ctrl + F`, and would allow me to enter a substring. The playlist would automatically hide all songs that did not match the substring as I typed. Looking at the shortcuts available in the Help screen (`F1`), I cannot find a shortcut that matches this behavior. Is there a way to re-enable it?

My `~/.ncmpcpp/keys` file contains no uncommented lines; I am using the default key configurations.

**Comment by arybczak** [comment]
It looks like you upgraded from 0.5.x, 0.6.x introduced a lot of changes (like p/P switch, also keys configuration file is no longer relevant, it was replaces with bindings that has incompatible format) and then 0.7.x also introduces some changes. Filtering was removed in 0.7.x as it was bugged and its functionality overlaps with plain search.

**Comment by ChimeraCoder** [comment]
0.5.x sounds right. I can get used to the keybinding changes, but the dynamic filtering was really convenient, and the plain search doesn't really substitute. Are there plans to bring this feature back?


And out of curiosity, what were the bugs? I don't see any in the issue tracker here about filtering - were the bugs on the daemon side?

**Comment by arybczak** [comment]
> Are there plans to bring this feature back?

No. What are the use cases you say search doesn't substitute?

**Comment by ChimeraCoder** [comment]
If I have a library with thousands or tens of thousands of songs, it's almost certain that I will have multiple different versions of the same song (e.g. covers by different artists, live recordings, acoustic versions, remixes, etc.). Filtering makes it easy for me to see which versions are available and select it, without having to toggle through each and every one manually.


To use an analogy, when I search for something on Google, I can see an entire page of results at a time, which is much more convenient than seeing each result individually and having to go back and forth to figure out which one I want to select.

**Comment by prietus** [comment]
I have playlists with more than 30k items from google play music, I suppose there were strong reasons to drop that functionality(?) I cannot find any bug about that. so may I kindly ask /why/?

**Comment by arybczak** [comment]
There were, although they might not seem very strong from the point of the end user. The main problems were complicated implementation which resulted in a lot of corner cases, obscure bugs and incredibly hard maintainability. Combine that with functionality being almost the same as search and misunderstandings that filtering the main playlist somehow affects how MPD plays tracks.and there you have it.

**Comment by ChimeraCoder** [comment]
I can understand that this caused difficulty with maintenance. But I strongly disagree that the functionality is almost the same as search - it really isn't. It would be if search displayed all of the results, but instead I have to painstakingly toggle through them one-by-one. It would be great if there is a way to bring search up to the level of functionality that filtering provided.

I'll be sad if this is being closed as a won't-fix, because it means that I'll be stuck running `0.5.x` from now on. The new version is unfortunately too slow to use, as it takes much longer to find the song I'm looking for with searching instead of filtering.

**Comment by arybczak** [comment]
What do you mean it takes much longer? It is performance or something else?

**Comment by eike2013** [comment]
+1 for reimplement the filter function! I miss it a lot, because it's way more comfortable to do a quick filter while browsing the music library instead of switching to the search window and enter information into the necessary fields, it's too time-consuming...

**Comment by arybczak** [comment]
?

You can still search with '/' or '?'.

**Comment by jcnoir** [comment]
I also miss the filter function a lot.

This is very different from the search screen (or /). 
Having a way to quickly "see" only matching songs in a long playlist was really a better user experience. Having to go to the search screen is too long if you do that a lot.
I tried to downgrade to the previous version but I got an issue with the boost libray version.

Please bring back the filter...

**Comment by jcherqui** [comment]
+1 for reimplement this function !

**Comment by jcherqui** [comment]
Please ! :(

**Comment by dlebrecht** [comment]
oh no!!! trust the users that there were use cases in that functionality, even if u guys don't get it. it was a happy day when i found out about C-f, and unhappy day today that i lost it.

**Comment by arybczak** [comment]
Ironically at some point I realized that indeed filtering is not as convenient for quick search as forward/backward searching. Combine that with mild frustration I had when I was on the receiving end of people removing functionality from their apps for no good reason and I decided to bring this feature back. I'm sorry for making this mistake and that it took so long to correct.

Reimplemented in 0.8_dev.

**Comment by jcnoir** [comment]
Thank you very much !!!

**Comment by dlebrecht** [comment]
awesome!! now the ctrl+f(un) is back. thanks

**Comment by kalj** [comment]
Fantastic! Thanks.

**Comment by jcherqui** [comment]
YES !!!! <3
