### ISSUE TITLE
Lyrics for streams

### ISSUE THREAD

**Issue by amerlyq** [arybczak/ncmpcpp#72]
Will it be too difficult to add support for automatic tags extraction, like %f into %a - %t?
Likewise specifying regex inside config, by which this extraction would take place, and from which tags.

Such option would allow to fetch lyrics for radio streams, which specify all tags in single one, so fetcher refuses to work. 
Alternative to this would be fuzzy search for that combined tag in lyrics databases, but it's less possible -- because radiostation like to add some trash into that string.

Third variant is to allow editing tags for streams, temporarily saving them in memory only.
It needs manually typing, but it's better than nothing.

I haven't found any workaround for this trouble, which would envolve only changes/scripting on user side, but if you mention some appropriate one, then this issue could be closed without code changes:)

**Comment by amerlyq** [comment]
How about third variant -- at least allow editing tags for streams? Is it too complex to implement?

**Comment by arybczak** [comment]
I lifted restriction for a song having tags - assuming that stream is somewhat sanely formatted, lyrics should be found by one of the fetchers.
