### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by hij1nx** [arybczak/ncmpcpp#73]
*Description*
When adding `visualizer_color = blue, cyan, green, yellow, magenta, red` to my config (copy pasted from the default config) i get an error saying `Error while processing option "visualizer_color": invalid value: blue, cyan, green, yellow, magenta, red`. I get the same error whenever trying to use 256 colors (ie `1_1`). 

*Version* 
ncmpcpp 0.6.7

*OS* 
Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; 2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by arybczak** [comment]
0.6.x doesn't have support for 256 colors.

**Comment by hij1nx** [comment]
Oh bummer. Any plans to support that? This project is great and I'd be happy to help! :)

**Comment by arybczak** [comment]
0.7.x has the support, although currently you can get it only by fetching master branch of this repo.

**Comment by hij1nx** [comment]
ah! awesome. I will just wait for 7.x to get into homebrew since it looks like it might happen soon. 
:beers:
