### ISSUE TITLE
[suggestion] Cancel modal operations by pression ESC

### ISSUE THREAD

**Issue by ttohin** [arybczak/ncmpcpp#78]
For example: When I press ```g``` I see a modal menu "Position to go". To hide the menu without changing the position I should keep input empty and press Enter. More than I'll error message "Invalid format". And the same with "find" menu.
I think It should be more "vi like" - Pressing ESC interrupts any modal operations.

**Comment by arybczak** [comment]
You can already do that with Ctrl-C/Ctrl-G. AFAIR I tried to make ESC also work, but readline didn't want to cooperate with me.

**Comment by trygveaa** [comment]
Ctrl-C/Ctrl-G doesn't seem to work for me. Nothing happens. (version 0.6.7)

**Comment by ttohin** [comment]
+1

**Comment by arybczak** [comment]
It's in 0.7.x.

**Comment by doronbehar** [comment]
Hello @arybczak,
I was wondering, have you triedever since this issue was closed to recheck this problem?

**Comment by arybczak** [comment]
I didn't. The issue is that readline can't seem to be able to recognise ESC while also be able to process special keys such as arrows. You're welcome to try making it do that though.

**Comment by matt-snider** [comment]
I tried doing this:

```
def_key "escape"
    abort_prompt
```

but I see [this code](https://github.com/arybczak/ncmpcpp/blob/81cb7a4f85287ce2671beca9023048f4de41ddf0/src/curses/window.cpp#L426) and realize it's not exposed in `actions.h` so it won't work. Is there any other way of doing it? Esc is really intuitive from other programs (e.g. vim)

**Comment by mrusme** [comment]
This still doesn't seem to be working out of the box unfortunately. 

Pressing ctrl+s in a playlist to open the sort dialog and then pressing escape doesn't lead to it being dismissed. Presseing `g` to open the "Position to go" prompt and then pressing escape doesn't do anything, leaving one stuck in the prompt.

Imho this issue needs to be re-opened as user experience is really bad in this regard. Generally it should imho be possible to dismiss any prompt/popup/... by default, using the escape key.

**Comment by kohane27** [comment]
I've found a workaround with `xremap`. We can map `jk` to `Ctrl-C`.

We need `--class dropdown_right` for `xremap` to identify this specific terminal window:

```bash
kitty --class dropdown_right zsh -i -c "ncmpcpp".
```

Then we can put the following in `~/.config/xremap/config.yml`:

```yml
keymap:
  - name: ncmpcpp
    application:
      only: [dropdown_right]
    remap:
      J:
        remap:
          K: C-c
        timeout_key: KEY_J
        timeout_millis: 40
```

Restart your `xremap` for it to take effect. Cheers!
