### ISSUE TITLE
Please follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by ManuelSchneid3r** [arybczak/ncmpcpp#79]
I.e. please use ~/.config/ncmpcpp/, if $XDG_CONFIG_HOME is not set.

See http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by arybczak** [comment]
This is already in 0.7.x.

**Comment by rolf1304** [comment]
Not entirely. The bindings file still defaults to, and the error.log is hardcoded to ~/.ncmpcpp
bindings should be in $XDG_CONFIG_HOME and error.log in $XDG_DATA_HOME.

**Comment by ManuelSchneid3r** [comment]
And dont forget the proper fallbacks. Most of the time the variables will not be set

**Comment by arybczak** [comment]
@rolf1304 It's not hardcoded, you just need to set ncmpcpp_directory.

**Comment by rolf1304** [comment]
Oh.. My bad!

**Comment by alichtman** [comment]
I'm seeing the same behavior described above:

```bash
$ ls .ncmpcpp
 error.log

$ alias ncmpcpp
ncmpcpp='ncmpcpp ncmpcpp_directory=/Users/alichtman/.config/ncmpcpp/'

$ ncmpcpp -v
ncmpcpp 0.8.2

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - outputs
 - visualizer
 - clock

encoding detection: enabled
built with support for: fftw ncurses taglib
```
