### ISSUE TITLE
Add album artist tag to sort options

### ISSUE THREAD

**Issue by adkow** [arybczak/ncmpcpp#80]
There is artist available to sort already but the thing is that in some cases it's not enough.
For example if I want to sort playlist by artist first it ends like this:
![playlist](https://cloud.githubusercontent.com/assets/14825909/10948041/c9ffd0fc-832b-11e5-8759-27c9bd69b53b.png)
The rest of album "The End of Evangelion" is somewhere else, in few places.

Of course it happens only when album contains more than one artist and one album artist.
I could try write this part of code, this issue is just to ask maintainer what he thinks about it.

**Comment by arybczak** [comment]
Sure, if you want you can add this, it should be a trivial change.
