### ISSUE TITLE
Not set up to work with latest ICU library 

### ISSUE THREAD

**Issue by InsidiousMind** [arybczak/ncmpcpp#82]
Hey, after the icu library update ncmpcpp no longer works. This is a pastebin from trying to install ncmpcpp.

http://pastebin.com/jEWTHwYW 

If i downgrade to icu 55.1-1 it works fine, but other applications on my computer don't work, so it's kind of counter-intuitive.

It also doesn't work with latest Boost Libraries:

```
ncmpcpp: error while loading shared libraries: libboost_filesystem.so.1.58.0: cannot open shared object file: No such file or directory
```

If you try starting NCMPCPP with correct Boost libraries but updated icu libraries:

```
ncmpcpp: error while loading shared libraries: libicudata.so.55: cannot open shared object file: No such file or directory
```

**Comment by arybczak** [comment]
I don't know about ICU (will check that), but it works fine with boost 1.58. This is most likely the problem with the binary package in your distribution.

**Comment by aldarionsevero** [comment]
I have a similar problem, but no libboost errors here. ncmpcpp works fine with  icu-56.1-1 but it does not with icu-57.x-x. I need to upgrade icu to work with other packages, and downgrade to use ncmpcpp...

**Comment by arybczak** [comment]
I never had any issues when upgrading icu (up to 1.57). These were most likely ABI issues specific to binary distros.

**Comment by avently** [comment]
@arybczak do you know now how to fix that error? I'm getting it every update of icu library. I use Manjaro and the latest version of icu is 62.1-1 from (named core/icu). Your app can't fine version 61. What to do in that situation?
