### ISSUE TITLE
font issue?

### ISSUE THREAD

**Issue by pvater** [arybczak/ncmpcpp#84]
i just upgraded to version 0.6.8.

it seems when i try to use the tag editor something goes horribly wrong - see here: http://imgur.com/a/iKt09
starting in playlist view (1. pic), when i for example type 'e' to go to the tag editor, immediatly followed by 'y' (without editing any tags) to go back, somehow suddenly the font is fucked (2. pic). weirdly enough when i do the same again ('e' followed by 'y'), it's becomes as it was before (1. pic).

now when i actually edit a tag, the font also gets screwed and stays that way even if i for example edit the tag to what it was before.

**Comment by arybczak** [comment]
See http://bugs.musicpd.org/view.php?id=3849.

**Comment by pvater** [comment]
thanks. but this was solved 2 years ago, and i'm running the latest version of taglib (1.10-1). do you think it's a still/again a bug in taglib?

**Comment by arybczak** [comment]
Maybe ncmpcpp you used earlier was compiled against taglib version with this bug? ABI breakages are tricky, you need to post more information about your distribution and history of taglib/ncmpcpp versions.

**Comment by pvater** [comment]
i use arch, just did a full update with 'pacman -Syu' yesterday. i removed and reinstalled ncmpcpp today, but to no avail. i don't know the versions of ncmpcpp/taglib i had before that.

**Comment by arybczak** [comment]
Reinstalling a binary package won't help, you need to recompile ncmpcpp against the current taglib version.
