### ISSUE TITLE
[Suggestion] Allow for vi-style editing for tags, etc.

### ISSUE THREAD

**Issue by davidjosepha** [arybczak/ncmpcpp#87]
It would be great to have the option to use vi-style editing for tags and other fields in ncmpcpp, like one can do with bash or zsh. Amazing, actually.

**Comment by arybczak** [comment]
It uses readline, so you just need to set readline to vi mode.

**Comment by davidjosepha** [comment]
Oh, thank you! I didn't realize you could do that. That's amazing. Finally! That one of the last things I've wanted from ncmpcpp, and apparently I could do it all along
