### ISSUE TITLE
select_found_items is not working

### ISSUE THREAD

**Issue by NicolasCARPi** [arybczak/ncmpcpp#89]
Hello,

It seems that select_found_items is not working.
I tried with latest commit on master branch. It does nothing. I want it to add to the current playlist the results of the search.

Can you reproduce this bug ?

**Comment by arybczak** [comment]
Nope, it works for me. Both Ctrl-/ and Ctrl-_ work. can you try to rebind it to a less "exotic" key and then try?

**Comment by NicolasCARPi** [comment]
Dear arybczak,

I'm binding it to 'A' which I believe is not an "exotic" key :p 
If I comment the binding, to get back the default, Ctrl-/ or Ctrl-_ doesn't work either. Nothing happens.
If I try any other key, or combination, it doesn't work.
So I have no way currently to add the search results to the current playlist :/

**Comment by arybczak** [comment]
Hmm. What do you mean by "the result of a search"?

**Comment by NicolasCARPi** [comment]
When on 'tab' 3, search screen, I make a search, then I want to copy all the results to the current playlist. Isn't that what select_found_items does ? Or at least select all so that I can press 'a' after and add it.

**Comment by arybczak** [comment]
Nope, that's not what it does. It selects items that are searched for in a list after using "Find item forward/backward" action. If you want to add all the items from search result, select them all ('v' by default) and then add them.

**Comment by NicolasCARPi** [comment]
Ok, thanks :)
