### ISSUE TITLE
git tags out of sync

### ISSUE THREAD

**Issue by anthraxx** [arybczak/ncmpcpp#90]
please keep your git tags in sync with your releases as i have watches on that to push new versions into the distro repository.

Its especially annoying to have git out of sync tags because your dir listing of http://ncmpcpp.rybczak.net/stable/ was deactivated.

I would highly appreciate if you keep your git tags in sync with the releases and push a 0.7 for both, github and git://repo.or.cz/ncmpcpp.git

**Comment by arybczak** [comment]
Sorry for the mess. I pushed the newest tag and also unblocked viewing contents of /stable.

**Comment by anthraxx** [comment]
@arybczak thank you very much, that was really a fast response!!! :+1: 
PS: Great tool, besides being the packager I'm also using it on a daily base :yum:
