### ISSUE TITLE
bindings file in XDG_CONFIG_HOME is not read

### ISSUE THREAD

**Issue by Eisfreak7** [arybczak/ncmpcpp#91]
When I read that ncmpcpp now supports the xdg config dir, I moved my .ncmpcpp directory to ~/.config/ncmpcpp.
However, my bindings file is not read. The configs work flawlessly, but the bindings are only read from ~/.ncmpcpp.
I don't assume this is intendet, since I consider bindings to also be configuration.

**Comment by arybczak** [comment]
You need to set "ncmpcpp_directory" variable to appropriate directory, otherwise it is assumed to be ~/.ncmpcpp.

**Comment by Eisfreak7** [comment]
Okay that works, sorry for not reading the manpage thourought enough.
However if you're interesed in suggestions, I think it'd be better to automatically fall back to the .config/ncmpcpp dir for the bindings as well as the configuration if the ncmpcpp_dir is not explicitly set to something different.
Also, files like error.log don't really belong in the .config dir, but rather in something like $XDG_DATA_HOME.
This solution is good enough for me however, these are just suggestions. Thanks for implementing the config dir, I'm happy about every program that stops cluttering my home directory.

**Comment by k0ral** [comment]
The `ncmpcpp_directory` doesn't fix the fact that there is an inconsistency:
- `config` is looked for into both `~/.ncmpcpp/` and `$XDG_CONFIG_HOME/ncmpcpp/`
- `bindings` is only looked for into `~/.ncmpcpp`

This is rather misleading and I believe it wouldn't hurt to look for `bindings` into `$XDG_CONFIG_HOME/ncmpcpp/` as well.

**Comment by nathanmusoke** [comment]
@mineo, will you be submitting a pull request with your patch? It would be nice to see this feature to keep config and data further separated.
