### ISSUE TITLE
jk keys not available to move cursor up and down

### ISSUE THREAD

**Issue by cpfaff** [arybczak/ncmpcpp#92]
Just installed version 0.6.4 on Ubuntu. Used ncmpcpp earlier and I think to remember there were default key mappings that allows moving around with the vim like key mappings `j and k` which is not working anymore. Can I get them back with the key mappings as the default mappings file that comes with the system does not give me a hint on that.

**Comment by cpfaff** [comment]
Solved: 

Created `~/.ncmpcpp/mappings` and added:

```
def_key "k"
	scroll_up
def_key "j"
	scroll_down
```

**Comment by mrjovanovic** [comment]
I have the same issue and the fix doesn't help. using version 0.7.4 on Debian stretch.

**Comment by arybczak** [comment]
The file should be called `bindings`, not `mappings`.

**Comment by mrjovanovic** [comment]
Thanks @arybczak, that solves it!
