### ISSUE TITLE
Cannot add individual song to playlist in "media_library" screen

### ISSUE THREAD

**Issue by sim590** [arybczak/ncmpcpp#95]
*Version*:
```
ncmpcpp 0.7

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info
 - outputs
 - visualizer
 - clock

encoding detection: enabled
built with support for: curl fftw ncurses taglib unicode
```

*Problem*:
When in `media_library` mode, going into the "Songs" column, selecting items (space -> select_item) and trying to add to the playlist (with a -> add_selected_items), I get the message : "No selected songs", but I have selected songs... Is there something wrong with my [bindings](http://ix.io/mYq) ?

![screenshot](http://i.imgur.com/cNaExHm.png)

**Comment by arybczak** [comment]
It's unfortunately a bug. 0.7.1 with a fix will be released shortly.
