### ISSUE TITLE
Visualizer time offset adjustment

### ISSUE THREAD

**Issue by hahiserw** [arybczak/ncmpcpp#96]
When I am looking at vizualizer I can see it outruns music (I can see some peaks and after a couple of milliseconds hear the sound). It also happens in mpdviz.

My guess is data in FIFO file is put a few moments ahead of what is about to be played.
Is there some way of changing how much ahead it is?

**Comment by arybczak** [comment]
This is a known problem. The workaround that seems to work is to periodically (i.e. each 30 seconds) toggle the fifo output. Visualizer does that, so the desynchronization should last for at most a couple of seconds if it ever becomes observable. Is your experience different?

**Comment by hahiserw** [comment]
I think it sometimes is as you described it. And sometimes it is synchronized, and after a couple of seconds it gets desynchronized. It stays that way until I toggle the FIFO output.

It's hard to tell. Now it looks like everything is perfectly synchronized.

**Comment by arybczak** [comment]
You can set a lower value of visualizer_sync_interval if it happens early.
