### ISSUE TITLE
Play only filtered songs

### ISSUE THREAD

**Issue by morfikov** [arybczak/ncmpcpp#97]
Ncmpcpp allows to set some filter using Ctrl+F key combination. Let's say I want to listen to a specific singer, so I just type his name. Is there a way to force ncmpcpp to play just the filtered results?

**Comment by arybczak** [comment]
Nope. Also note that filtering was removed in 0.7.

**Comment by jcherqui** [comment]
+1 for reimplement this function !

**Comment by jcherqui** [comment]
+1
