### ISSUE TITLE
Better lyrics retrieval 

### ISSUE THREAD

**Issue by owenversteeg** [arybczak/ncmpcpp#98]
Currently, some lyrics return "see examplelyricsite.com for lyrics", presumably because someone made some sort of copyright claim on the lyrics that forced them to not be accessible via API. Would it be possible to do a simple check on the lyrics returned (see if they are shorter than, say, 50 characters, and contain ".com") and if so, reject them and fetch lyrics from another site?

I'm trying to find an example of this; if anyone reading this has any examples of songs with this result when looking up lyrics I'd be grateful.

**Comment by arybczak** [comment]
What site does return such messages?

**Comment by arybczak** [comment]
No feedback, closing.
